// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L22Pset/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L22Pset",
  level: 1,
  name: "Pointwise of Uniform Convergence",
  theoremName: "L22Pset_1",
  statement: `(f : ℕ → ℝ → ℝ) (F : ℝ → ℝ) (hfF : UnifConv f F) :
  ∀ x, SeqLim (fun n ↦ f n x) (F x)`,
  objects: "(f : ℕ → ℝ → ℝ) (F : ℝ → ℝ)",
  assumptions: "(hfF : UnifConv f F)",
  goal: "∀ x, SeqLim (fun n ↦ f n x) (F x)",
  introduction: `
# Level 1: Pointwise of Uniform Convergence

Prove that if a sequence of functions converges uniformly to a limit function,
then it also converges pointwise.

`,
};

export default level;
