// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L22Pset/L02.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L22Pset",
  level: 2,
  name: "Continuity Exercise",
  theoremName: "L22Pset_2",
  statement: ": FunCont (fun x ↦ x ^ 3)",
  goal: "FunCont (fun x ↦ x ^ 3)",
  introduction: `
# Level 2: Continuity Exercise

Prove that \`x ↦ x ^ 3\` is continuous.

`,
  conclusion: `
`,
};

export default level;
