// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L22Pset/L03.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L22Pset",
  level: 3,
  name: "Differentiability Exercise",
  theoremName: "L22Pset_3",
  statement: `: ∃ g : ℝ → ℝ,
  FunDeriv (fun x ↦ x ^ 3) g`,
  goal: "∃ g : ℝ → ℝ, FunDeriv (fun x ↦ x ^ 3) g",
  introduction: `
# Level 3: Differentiability Exercise

Show that \`x ↦ x ^ 3\` is differentiable.

`,
  conclusion: `
`,
};

export default level;
