// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L22Pset/L04.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L22Pset",
  level: 4,
  name: "Integral Exercise",
  theoremName: "L22Pset_4",
  statement: `(n : ℕ) :
  ∑ i ∈ Finset.range n, ((i : ℝ) + 1) ^ 2 = ((n : ℝ) * (n + 1) * (2 * n + 1)) / 6`,
  objects: "(n : ℕ)",
  goal: "∑ i ∈ Finset.range n, ((i : ℝ) + 1) ^ 2 = ((n : ℝ) * (n + 1) * (2 * n + 1)) / 6",
  introduction: `
# Level 4: Integral Exercise

As you may imagine, the proof that \`f(x) = x ^ 2\` is integrable will involve the following formula for the sum of squares:

\`∑ i ∈ Finset.range n, (i + 1) ^ 2 = (n * (n + 1) * (2 * n + 1)) / 6\`.

(All as real numbers.) Prove it. Then in natural language, prove that \`f(x) = x ^ 2\` is integrable on \`[a,b]\`.

`,
  conclusion: `
`,
};

export default level;
