// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L9Pset/L9Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L9Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L9Pset_2",
  statement: `(N : ℕ) :
    ∃ k : ℕ, N * (N + 1) = 2 * k`,
  objects: "(N : ℕ)",
  goal: "∃ k : ℕ, N * (N + 1) = 2 * k",
  introduction: `# Problem 2

Prove that \`N * (N + 1)\` is always even.

`,
  conclusion: "",
};

export default level;
