// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L9Pset/L9Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L9Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L9Pset_1",
  statement: `(a : ℕ → ℝ) (L : ℝ) (ha : SeqLim a L) :
    SeqBdd a`,
  objects: "(a : ℕ → ℝ) (L : ℝ)",
  assumptions: "(ha : SeqLim a L)",
  goal: "SeqBdd a",
  introduction: `# Problem 1

Prove the same theorem as \`Bdd_of_ConvNonzero\`, but without the assumption that \`L ≠ 0\`. (Hint: break
the proof into cases, and the case \`L ≠ 0\` should just be an appeal to \`Bdd_of_ConvNonzero\`. What
do you do in the other case?)

`,
  conclusion: "",
};

export default level;
