// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L9Pset/L9Pset3.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L9Pset",
  level: 3,
  name: "Problem 3",
  theoremName: "L9Pset_3",
  statement: `(N : ℕ) :
    2 * ∑ k ∈ range N, (k + 1) = N * (N + 1)`,
  objects: "(N : ℕ)",
  goal: "2 * ∑ k ∈ range N, (k + 1) = N * (N + 1)",
  introduction: `# Problem 3

Prove that \`2 * (1 + 2 + ... + N) = N * (N + 1)\`.

`,
  conclusion: "",
};

export default level;
