// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L17Pset/L05'.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L17Pset",
  level: 2,
  name: "Monotone Limit Bound",
  theoremName: "L17Pset_2",
  statement: `MonotoneLimitBound {a : ℕ → ℝ} (amono : Monotone a) {L : ℝ} (ha : SeqLim a L) : ∀ n,
  a n ≤ L`,
  objects: "{a : ℕ → ℝ} {L : ℝ}",
  assumptions: "(amono : Monotone a) (ha : SeqLim a L)",
  goal: "∀ n, a n ≤ L",
  introduction: `
# Level 2: Monotone Limit Bound

Prove the theorem \`MonotoneLimitBound\`:
Suppose that a sequence \`a : ℕ → ℝ\` is \`Monotone\` and has limit \`L\`. Then
for every \`n\`, \`a n ≤ L\`.

`,
  conclusion: `
`,
};

export default level;
