// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L17Pset/L05.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L17Pset",
  level: 1,
  name: "Monotonicity of Series",
  theoremName: "L17Pset_1",
  statement: "Monotone_of_NonNegSeries {a : ℕ → ℝ} (ha : ∀ n, 0 ≤ a n) : Monotone (Series a)",
  objects: "{a : ℕ → ℝ}",
  assumptions: "(ha : ∀ n, 0 ≤ a n)",
  goal: "Monotone (Series a)",
  introduction: `
# Level 1: Monotonicity of Series

Prove \`Monotone_of_NonNegSeries\`:
If \`0 ≤ a n\`, then \`Series a\` is Monotone.

`,
  conclusion: `
`,
};

export default level;
