// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L17Pset/L06.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L17Pset",
  level: 3,
  name: "The Comparison Test",
  theoremName: "L17Pset_3",
  statement: `ComparisonTest {a b : ℕ → ℝ} (ha : ∀ n, 0 ≤ a n) (hab : ∀ n, a n ≤ b n)
  (hb : SeriesConv b) : SeriesConv a`,
  objects: "{a b : ℕ → ℝ} (hb : SeriesConv b)",
  assumptions: "(ha : ∀ n, 0 ≤ a n) (hab : ∀ n, a n ≤ b n)",
  goal: "SeriesConv a",
  introduction: `
# Level 3: The Comparison Test

Prove the \`ComparisonTest\`: if \`a n\` is dominated by a convergent series,
then it also converges.

(In lecture 17, we proved a special case of this theorem, when we started studying the Basel Problem.)

`,
  conclusion: `
`,
};

export default level;
