// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L24Pset/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L24Pset",
  level: 1,
  name: "Lipschitz implies Uniformly Continuous",
  theoremName: "L24Pset_1",
  statement: `(f : ℝ → ℝ) (K : ℝ) (hK : K > 0) (hf : ∀ x y : ℝ, |f y - f x| ≤ K * |y - x|) (a b : ℝ) :
  UnifContOn f (Icc a b)`,
  objects: "(f : ℝ → ℝ) (K : ℝ) (a b : ℝ)",
  assumptions: "(hK : K > 0) (hf : ∀ x y : ℝ, |f y - f x| ≤ K * |y - x|)",
  goal: "UnifContOn f (Icc a b)",
  introduction: `
# Level 1: Lipschitz implies Uniformly Continuous

A function \`f : ℝ → ℝ\` is called *Lipschitz* if there exists a constant \`K > 0\` such that for all \`x, y ∈ ℝ\`,

\`|f(y) - f(x)| ≤ K * |y - x|\`.

In this problem, you will prove that every Lipschitz function is uniformly continuous.

`,
  conclusion: `
`,
};

export default level;
