// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L24Pset/L02.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L24Pset",
  level: 2,
  name: "Open Balls are Open",
  theoremName: "L24Pset_2",
  statement: ": True",
  goal: "True",
  introduction: `
# Level 2: Open Balls are Open

Prove that an open ball \`Ball x r\` is open, as a set.

`,
  conclusion: `
`,
};

export default level;
