// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Levels/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture18",
  level: 1,
  name: "Absolute Convergence Implies Convergence",
  theoremName: "Lecture18_1",
  statement: "Conv_of_AbsSeriesConv {a : ℕ → ℝ} (ha : AbsSeriesConv a) : SeriesConv a",
  objects: "{a : ℕ → ℝ} (ha : AbsSeriesConv a)",
  goal: "SeriesConv a",
  introduction: `
# Level 1: Absolute Convergence Implies Convergence

In this level, we introduce the concept of **absolute convergence** and prove one of the fundamental theorems about series: if a series converges absolutely, then it converges.

## New definition: \`AbsSeriesConv\`

A series \`Series a\` is said to converge *absolutely* (\`AbsSeriesConv\`) if the series of absolute values
\`Series (fun n ↦ |a n|)\` converges.

This is a *stronger* condition than ordinary convergence. For instance, the alternating harmonic series
$$\\sum_{k=1}^{\\infty} \\frac{(-1)^{k+1}}{k} = 1 - \\frac{1}{2} + \\frac{1}{3} - \\frac{1}{4} + \\cdots$$
converges but does *not* converge absolutely (since the harmonic series diverges).

## The Main Result

**Theorem** (\`Conv_of_AbsSeriesConv\`): If a series converges absolutely, then it converges.

In other words: *absolute convergence implies convergence*.

## Proof Strategy

The key insight is that if the series of absolute values converges, then it is Cauchy, which means the tails of the series get arbitrarily small. By the triangle inequality, if $\\sum |a_k|$ is small, then $|\\sum a_k|$ is also small.

We will use two helper lemmas (to be proved as homework):
- \`DiffOfSeries\`: The difference of partial sums equals the sum over the interval
- \`Series_abs_add\`: The triangle inequality for finite sums

Your task: Prove \`Conv_of_AbsSeriesConv\` using the Cauchy criterion and these lemmas.
`,
  conclusion: `
# Congratulations!

You've just proven one of the most important theorems in the theory of infinite series!

## What We've Learned

The theorem **absolute convergence implies convergence** gives us a powerful tool: to show a series converges, it often suffices to show it converges absolutely. This is frequently easier because we can ignore the signs of the terms.

## Key Technique

The proof relied on the **Cauchy criterion**: a series converges if and only if its partial sums form a Cauchy sequence. We showed that if the series of absolute values is Cauchy, then the original series must be Cauchy too, using the triangle inequality to bound the partial sums.

## Why This Matters

This theorem is the foundation for:
- **Comparison tests**: If $|a_n| \\leq b_n$ and $\\sum b_n$ converges, then $\\sum a_n$ converges absolutely (hence converges)
- **Rearrangement theorems**: Absolutely convergent series can be rearranged without changing their sum
- **Function series**: Power series and Fourier series often converge absolutely in their domains

## The Converse is False!

Remember: The converse is *not* true. There exist series that converge but do not converge absolutely. These are called **conditionally convergent** series, and they behave very differently from absolutely convergent series (as we'll see in the next level with the Alternating Series Test)!

The distinction between absolute and conditional convergence is one of the most important concepts in real analysis.
`,
};

export default level;
