// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Levels/L02.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture18",
  level: 2,
  name: "Alternating Series Test",
  theoremName: "Lecture18_2",
  statement: "AlternatingSeriesTest {a : ℕ → ℝ} (ha : Antitone a) (aLim : SeqLim a 0) : SeriesConv (fun n ↦ (-1)^n * a n)",
  objects: "{a : ℕ → ℝ}",
  assumptions: "(ha : Antitone a) (aLim : SeqLim a 0)",
  goal: "SeriesConv (fun n ↦ (-1)^n * a n)",
  introduction: `
# Level 2: Alternating Series Test

In this level, we prove one of the most elegant and useful results in the theory of infinite series: the **Alternating Series Test**, also known as the **Leibniz Test** (named after Gottfried Wilhelm Leibniz, who discovered it in the 17th century).

## The Setting

Consider an alternating series—one where the signs alternate between positive and negative:

$a_0 - a_1 + a_2 - a_3 + a_4 - \\cdots = \\sum_{n=0}^{\\infty} (-1)^n \\cdot a_n$

When does such a series converge?

## The Theorem

**Theorem** (\`AlternatingSeriesTest\`): Suppose \`a : ℕ → ℝ\` is an \`Antitone\` sequence (meaning $a_0 \\geq a_1 \\geq a_2 \\geq \\cdots$) that converges to \`0\`. Then the alternating series

$\\sum_{n=0}^{\\infty} (-1)^n \\cdot a_n$

converges.

In other words: *if the terms decrease to zero, then the alternating series converges*.

**Note**: By \`AntitoneLimitBound\` (to be proved in homework), since $a_n \\to 0$ and $a$ is antitone, we automatically have $a_n \\geq 0$ for all $n$.

## Classic Examples

- The alternating harmonic series: $\\sum_{k=1}^{\\infty} \\frac{(-1)^{k+1}}{k} = 1 - \\frac{1}{2} + \\frac{1}{3} - \\frac{1}{4} + \\cdots$ converges to $\\ln 2$
- The Leibniz formula for $\\pi$: $\\sum_{k=0}^{\\infty} \\frac{(-1)^k}{2k+1} = 1 - \\frac{1}{3} + \\frac{1}{5} - \\frac{1}{7} + \\cdots = \\frac{\\pi}{4}$

## Proof Strategy

The idea is to show that the **even** partial sums and **odd** partial sums both converge to the same limit:
- Even partial sums: $S_{2n} = a_0 - a_1 + a_2 - \\cdots - a_{2n-1}$ form a monotone increasing, bounded sequence
- Odd partial sums: $S_{2n+1} = a_0 - a_1 + a_2 - \\cdots + a_{2n}$ form a monotone decreasing, bounded sequence
- The difference $S_{2n+1} - S_{2n} = a_{2n} \\to 0$, so they converge to the same limit

This will require several technical lemmas (all to be proved in homework), but the main proof brings them all together beautifully!

Your task: Prove the \`AlternatingSeriesTest\` by showing both even and odd subsequences of partial sums converge to the same limit.

## New Theorems: look up: \`AntitoneLimitBound\`, \`CoherenceOfReals\`, \`SeqEvenOdd\`, \`MonotoneSeriesEven\`, \`AntitoneSeriesOdd\`, \`BddSeriesEven\`, \`BddSeriesOdd\`, and \`DiffGoesToZero\`.
`,
  conclusion: `
# Congratulations!

You've just proven the **Alternating Series Test**—one of the most beautiful and practical convergence tests in real analysis!

## What We've Accomplished

This theorem tells us that an alternating series $\\sum_{n=0}^{\\infty} (-1)^n \\cdot a_n$ converges whenever:
1. The terms $a_n$ are decreasing (antitone)
2. The terms approach zero: $a_n \\to 0$

These conditions are remarkably easy to check in practice!

## The Power of the Proof Technique

The proof strategy—analyzing even and odd partial sums separately—is a powerful technique that appears throughout analysis:
- The even partial sums squeeze upward toward the limit
- The odd partial sums squeeze downward toward the limit
- They meet in the middle as $a_n \\to 0$

This "pinching" or "squeezing" argument is elegant and intuitive.

## A Crucial Observation: Conditional Convergence

Notice that the alternating harmonic series $\\sum_{k=1}^{\\infty} \\frac{(-1)^{k+1}}{k}$ converges by this test, but its absolute value series $\\sum_{k=1}^{\\infty} \\frac{1}{k}$ (the harmonic series) diverges!

This makes it **conditionally convergent**—it converges, but not absolutely. As we discussed in the introduction to this lecture, such series have remarkable properties: their sums can be rearranged to converge to *any* real number, or even to diverge! This is **Riemann's Rearrangement Theorem**, which we'll explore in future levels.

## Historical Note

Leibniz discovered this test in the 1670s while studying his famous series for $\\pi/4$ (also known centuries before to the Indian Madhava). It was one of the first convergence tests ever discovered, and it remains one of the most useful and elegant results in all of analysis.

## What's Next?

With absolute convergence (Level 1) and the alternating series test (Level 2) under our belt, we're now ready to explore the deep and sometimes counterintuitive theory of **rearrangements of series**—where the distinction between absolute and conditional convergence becomes truly dramatic!
`,
};

export default level;
