// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L17Levels/L03.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture17",
  level: 3,
  name: "Series Order Theorem",
  theoremName: "Lecture17_3",
  statement: "SeriesOrderThm {a b : ℕ → ℝ} (hab : ∀ n, a n ≤ b n) : ∀ n, Series a n ≤ Series b n",
  objects: "{a b : ℕ → ℝ}",
  assumptions: "(hab : ∀ n, a n ≤ b n)",
  goal: "∀ n, Series a n ≤ Series b n",
  introduction: `
# Level 3: Series Order Theorem

One of the most fundamental properties of series is that they **respect inequalities**: if one sequence is term-by-term less than or equal to another, then their partial sums satisfy the same relationship.

## The Theorem

**Series Order Theorem:** If \`a n ≤ b n\` for all \`n\`, then:
\`Series a n ≤ Series b n\` for all \`n\`

In other words:
\`∑ k ∈ range n, a k ≤ ∑ k ∈ range n, b k\`

## Why This Matters

This seemingly simple result is the foundation for **comparison tests** in series theory. If we know that:
- \`0 ≤ a n ≤ b n\` for all \`n\`, and
- \`∑ b n\` converges to some value \`M\`

Then we can conclude that \`∑ a n\` also converges, and moreover \`∑ a n ≤ M\`.

We'll use this exact strategy in the next level to prove the Basel series converges!

## The Proof Strategy

This is a straightforward **induction** argument:
- **Base case (n=0):** Both sums are empty, so \`0 ≤ 0\` ✓
- **Inductive step:** If $\\sum_{k<n} a_k \\le \\sum_{k<n} b_k$ and \`a n ≤ b n\`, then adding \`a n\` to the left and \`b n\` to the right preserves the inequality.

## Your Task

Prove \`SeriesOrderThm\`: given \`a n ≤ b n\` for all \`n\`, show that \`Series a n ≤ Series b n\` for all \`n\`.

**Hints:**
- Use induction with \`induction' n with n hn\`
- The base case can be handled with \`bound\`
- For the inductive step, use \`sum_range_succ\` to split off the last term
- Then combine the inductive hypothesis with \`hab n\` using \`linarith\`

This is a clean, elegant proof—enjoy the simplicity!
`,
  conclusion: `
Perfect! You've proven a fundamental monotonicity property of series.

## What You've Proven

**Theorem (SeriesOrderThm):** If \`a n ≤ b n\` for all \`n\`, then:
\`Series a n ≤ Series b n\` for all \`n\`

That is, term-by-term inequalities are preserved in partial sums.

## The Proof Technique

Your induction proof was beautifully straightforward:
- **Base case:** Empty sums are equal, so \`0 ≤ 0\`
- **Inductive step:** Split each sum using \`sum_range_succ\`, apply the inductive hypothesis to the first \`n\` terms, and use \`a n ≤ b n\` for the last term

The inequality $∑_{k<n} a k + a n ≤ ∑_{k<n} b k + b n$ followed immediately from combining two simpler inequalities!

## Why This Is Powerful

This theorem is the cornerstone of **comparison tests** for series convergence. Here's the typical application:

**Comparison Test Setup:**
- Suppose \`0 ≤ a n ≤ b n\` for all \`n\`
- Suppose the series \`∑ b n\` converges to some limit \`B\`

**Conclusion:** The series \`∑ a n\` also converges, and \`∑ a n ≤ B\`.

**Why?** By your theorem, every partial sum satisfies \`Series a n ≤ Series b n ≤ B\`. So the sequence \`Series a n\` is monotone increasing (adding positive terms) and bounded above by \`B\`. Therefore it must converge!

## Taking Limits

An important consequence: if \`a n ≤ b n\` for all \`n\`, and both infinite series converge, then:
\`∑_{k=0}^∞ a k ≤ ∑_{k=0}^∞ b k\`

This follows by taking limits on both sides of your partial sum inequality. Limits preserve weak inequalities!

## Preview: The Basel Problem

In the next level, we'll use this theorem to prove that the famous **Basel series** converges:
\`∑ k, 1/(k+2)² = 1/4 + 1/9 + 1/16 + 1/25 + ...\`

The strategy: compare it with the Leibniz series! Since \`1/(k+2)² ≤ 1/((k+1)(k+2))\`, your theorem tells us the Basel series has smaller partial sums. Since the Leibniz series converges to 1, the Basel series is bounded above by 1.

Combined with the fact that the Basel series is monotone increasing (adding positive terms), this will prove convergence!

## General Principle

Your theorem exemplifies a key principle in analysis: **order structure is preserved under limits**. This makes inequality reasoning a powerful tool throughout real analysis.

---

**Next:** Time to tackle the Basel Problem—one of the most famous series in mathematical history!
`,
};

export default level;
