// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L15Levels/L01_completenessAlt.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture15",
  level: 1,
  name: "Completeness",
  theoremName: "Lecture15_1",
  statement: `(q : ℕ → ℕ → ℚ) (hq : ∀ n, IsCauchy (q n))
  (hx : ∀ ε > 0, ∃ N, ∀ n ≥ N, ∀ m ≥ n, SeqDiffBy (q m) (q n) ε) :
  ∃ (y : ℕ → ℚ), (IsCauchy y) ∧
  ∀ ε > 0, ∃ N, ∀ n ≥ N, SeqDiffBy (q n) y ε`,
  objects: "(q : ℕ → ℕ → ℚ)",
  assumptions: "(hq : ∀ n, IsCauchy (q n)) (hx : ∀ ε > 0, ∃ N, ∀ n ≥ N, ∀ m ≥ n, SeqDiffBy (q m) (q n) ε)",
  goal: "∃ (y : ℕ → ℚ), (IsCauchy y) ∧ ∀ ε > 0, ∃ N, ∀ n ≥ N, SeqDiffBy (q n) y ε",
  introduction: `
# Level 1 **Big Boss:**  Completeness!

We now know that Cauchy sequences of rational numbers converge to real numbers. (Because they *are* real numbers.) Let's record this as a theorem:

## New theorem: \`Conv_of_IsCauchy\` : If a sequence \`(a : ℕ → ℚ)\` satisfies \`IsCauchy a\`, then that implies that \`SeqConv a\`.

Given that a limit exists, let us make the following

## New definition: \`Real_of_CauSeq\`. This takes \`IsCauchy a\` and returns a real number.

This real number does what we want:

## New theorem: \`SeqLim_of_Real_of_Cau\` : \`ha : IsCauchy (a : ℕ → ℚ)\` implies that \`SeqLim a (Real_of_CauSeq ha)\`.


Ok, but what about Cauchy sequences of real numbers? Do we need a whole other number system (the "hyperreals" or perhaps "surreals", for the Conway fans out there...)
to capture limits of reals?

No! And this is a general phenomenon: when you
"complete" a space by replacing it with equivalence classes of Cauchy sequences from
that space, the space itself is automatically "complete", that is, all Cauchy
sequences in the completed space already converge in the same. Let's prove it for the reals!

So again, we want to show that:
any Cauchy sequence of *real* numbers converges to a real number.
But we just learned that real numbers are themselves Cauchy sequences of rationals
(or rather, equivalence classes thereof).
Now that real numbers are represented by Cauchy sequences of rationals, what does it mean for $x_n$ to be a Cauchy sequence of reals? A Cauchy sequence of Cauchy sequences?? Let's unpack that.

Let's say that we have an infinite sequence of real numbers, \`x : ℕ → ℝ\`, thought of as \`x = (x₀, x₁, x₂, ...)\`.
 Each
real \`xₙ\` is secretly represented by a Cauchy sequence \`(qₙ₀, qₙ₁, qₙ₂,...)\` of rationals.
So each \`xₙ\` is a map \`ℕ → ℚ\`, and the original \`x\` is actually a map:

\`q : ℕ → ℕ → ℚ\`

That is, \`x\` is really a double-indexed array of rationals:

\`\`\`
       j=0    j=1    j=2    j=3    ...
i=0:   q₀₀    q₀₁    q₀₂    q₀₃    ...   ← represents x₀
i=1:   q₁₀    q₁₁    q₁₂    q₁₃    ...   ← represents x₁
i=2:   q₂₀    q₂₁    q₂₂    q₂₃    ...   ← represents x₂
i=3:   q₃₀    q₃₁    q₃₂    q₃₃    ...   ← represents x₃
 ⋮      ⋮      ⋮      ⋮      ⋮
\`\`\`

Each **row** is a Cauchy sequence of rationals \`qₙₘ\` converging to the corresponding real \`xₙ\`. Wild! Let's call \`hq\` the condition that each of these rows is a Cauchy sequence:

\`hq : ∀ n, IsCauchy (q n)\`

Then to say that this sequence (of sequences) \`xₙ\` is itself "Cauchy" is to say (as we already know) that:

\`∀ ε > 0, ∃ N, ∀ n ≥ N, ∀ m ≥ n, |Real_of_CauSeq (hq m) - Real_of_CauSeq (hq n)| < ε\`

Now, let's assume this condition on our Cauchy sequence (of sequences) \`x\`. Our goal is to show that this sequence has a real limit, that is,
that there is a single sequence \`y : ℕ → ℚ\`, satisfying

\`hy : IsCauchy y\`

and so that \`xₙ → y\`, which means:

\`SeqLim (fun n ↦ Real_of_CauSeq (hq n)) (Real_of_CauSeq hy)\`.

How are we supposed to construct such a thing?!?!

The key insight (reminiscent of Cantor's **diagonalization** arguments, very prevalent
in real analysis): we need to extract a single sequence of rationals from this array!

**The naive attempt:** Take the diagonal sequence \`(q₀₀, q₁₁, q₂₂, q₃₃, ...)\`

**The problem:** Each row converges at **its own rate**! Row \`k\` might need to go out to
index \`1000k\` before it's within \`ε\` of its limit, and row \`k+1\` might need to go to index \`k^2\`, etc. But the diagonal only samples row \`k\`
at position \`k\`, which might be way too early!

**The solution:** For each row \`k\`, we need to pick an index \`N(k)\` that's far enough
out that row \`k\` has "converged well enough" by that point. Then we take:

\`y k = q k (N (k))\`

This sequence \`y\` will be Cauchy, and it will represent the limit of our sequence of reals!

**How to choose \`N(k)\`?** Use the fact that each \`x k\` (as a real number) is the limit of
its Cauchy sequence. So for any tolerance (say \`1/k\`, or rather, \`1/(k+1)\` so it's always strictly positive), there exists an index \`N(k)\`
so that for all \`n ≥ m ≥ N(k)\`, \`q k m\` stays within \`1/(k+1)\` of \`q k n\`. *That* is what we'll choose!

**Your task:** Construct this sequence \`y\`, prove it's Cauchy, and prove that the
sequence of reals converges to the real represented by \`y\`.

`,
  conclusion: `
`,
};

export default level;
