// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L19Levels/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture19",
  level: 1,
  name: "More Flexible Cauchy",
  theoremName: "Lecture19_1",
  statement: `StrongCauchy_of_AbsSeriesConv
    {a : ℕ → ℝ} (ha : AbsSeriesConv a) {ε : ℝ} (hε : ε > 0) :
    ∃ N, ∀ (S : Finset ℕ), (∀ k ∈ S, k ≥ N) → ∑ k ∈ S, |a k| < ε`,
  objects: "{a : ℕ → ℝ} (ha : AbsSeriesConv a) {ε : ℝ}",
  assumptions: "(hε : ε > 0)",
  goal: "∃ N, ∀ (S : Finset ℕ), (∀ k ∈ S, k ≥ N) → ∑ k ∈ S, |a k| < ε",
  introduction: `
# Level 1: More Flexible Cauchy

In this level, we prove a stronger version of the Cauchy criterion that will be essential for understanding rearrangements of series.

## The Main Result

**Theorem** (\`StrongCauchy_of_AbsSeriesConv\`): If a series converges absolutely, then for any \`ε > 0\`, there exists \`N\` such that for *any* finite set \`S : Finset ℕ\` whose elements all exceed \`N\`, we have:

\`∑ k ∈ S, |a k| < ε\`

## Why This is Stronger

The usual Cauchy criterion only tells us that consecutive intervals \`[n, m)\` have small sum. This theorem says something much more powerful: *any* finite collection of sufficiently large-index terms has small sum, regardless of whether the indices are consecutive or scattered.

## The Key Insight

For absolutely convergent series, the tail becomes arbitrarily small. Any finite subset of the tail is contained in some interval, and by monotonicity of sums of nonnegative terms, the sum over the subset is bounded by the sum over the interval.

This flexibility is exactly what we need to handle rearrangements, where terms might appear in a completely different order.

## New Theorems

- \`sum_le_sum_of_nonneg\`: If \`S ⊆ T\` and all values are nonnegative, then \`∑ i ∈ S, f i ≤ ∑ i ∈ T, f i\`
- \`sum_le_mem_of_nonneg\`: If \`x ∈ S\` and all values are nonnegative, then \`f x ≤ ∑ i ∈ S, f i\`
- \`mem_Ico\`: Characterizes membership in half-open intervals \`[a, b)\`

Your task: Prove the strong Cauchy property using these tools!
`,
  conclusion: `
# Congratulations!

You've just proven the **Strong Cauchy Property** for absolutely convergent series—a crucial stepping stone toward the Rearrangement Theorem!

## What We've Accomplished

This theorem shows that absolute convergence gives us tremendous flexibility in how we sum the terms. Not only do consecutive intervals have small sum (the usual Cauchy property), but *any* finite collection of sufficiently large-index terms has arbitrarily small sum.

This is much more flexible than the standard Cauchy criterion, which only considers intervals \`[n, m)\`. Here, we could pick scattered indices like \`{100, 137, 1000000, 10^10}\` and still guarantee the sum is small, as long as all indices exceed our threshold \`N\`.

## The Key Technique

The proof uses a clever bounding argument:
1. Every finite set has a maximum element, so we can find an interval containing it
2. The finite set is a subset of this interval
3. Since all terms are nonnegative (we're working with absolute values), monotonicity gives us the bound we need

## Why This Matters for Rearrangements

When we rearrange a series, terms appear in a completely different order. At some point in the rearranged series, we'll have covered all the early terms, but there will be scattered later terms we haven't seen yet.

The strong Cauchy property tells us that these scattered "missing" terms contribute negligibly to the sum, because they all have large indices. This is the key to showing that rearrangements don't change the sum!

## Looking Ahead

In the next level, we'll formalize what a rearrangement is and prove that rearrangements eventually "catch up" with the original ordering. Combined with this strong Cauchy property, we'll have all the tools needed to prove the magnificent Rearrangement Theorem.
`,
};

export default level;
