// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L19Levels/L03.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture19",
  level: 3,
  name: "**Big Boss**: Rearrangement Theorem",
  theoremName: "Lecture19_3",
  statement: `RearrangementThm {a : ℕ → ℝ} (ha : AbsSeriesConv a) :
  ∃ L, ∀ (σ : ℕ → ℕ) (_ : Rearrangement σ), SeriesLim (a ∘ σ) L`,
  objects: "{a : ℕ → ℝ} (ha : AbsSeriesConv a)",
  goal: "∃ L, ∀ (σ : ℕ → ℕ) (_ : Rearrangement σ), SeriesLim (a ∘ σ) L",
  introduction: `
# Level 3 **Big Boss**: Rearrangement Theorem

This is it—the moment we've been building toward! We're about to prove one of the most profound and beautiful theorems in all of real analysis.

## The Fundamental Theorem

**Theorem** (\`RearrangementThm\`): If a series \`∑ a_n\` converges absolutely, then for any rearrangement \`σ : ℕ → ℕ\`, the rearranged series \`∑ a_(σ(n))\` converges to the same limit.

In symbols: If \`AbsSeriesConv a\`, then there exists \`L\` such that, for all \`Rearrangement\`s, \`σ\`, (including the identity) and \`SeriesLim (a ∘ σ) L\`.

## The Deep Meaning

This theorem reveals a profound truth about infinite summation:

**Infinite summation is commutative if and only if the series is absolutely convergent.**

For finite sums, we can add terms in any order—the sum doesn't change. This theorem says that absolute convergence is *exactly* what's needed to extend this property to infinite sums!

## Why This is a Big Deal

Remember from Lecture 18 how we showed that rearranging the infinite matrix changed its sum from 0 to -2? That's because those series were *not* absolutely convergent.

For absolutely convergent series, we have complete freedom: reorder the terms however you like, and the sum stays the same. It's as if absolute convergence gives infinite series the "finite property" of commutativity.

## New Theorems

- \`Series_image\`: Relates the rearranged series to a sum over the image of \`σ\`
- \`sum_sdiff\`: Handles sums over set differences: \`∑ (S₂ \\ S₁) + ∑ S₁ = ∑ S₂\`
- \`abs_sum_le_sum_abs\`: Triangle inequality for finite sums

## The Proof Strategy

We'll combine everything from Levels 1 and 2:
1. The strong Cauchy property tells us that scattered large-index terms contribute negligibly
2. The eventually covers property tells us that rearrangements eventually include all early terms
3. We'll show the rearranged series stays close to the original by bounding the "uncovered" terms

This is a technical proof, but the idea is beautiful: absolute convergence gives us enough "slack" that scrambling the order doesn't matter.

Your task: Prove the Rearrangement Theorem—and unlock one of the deepest truths about infinite series!
`,
  conclusion: `
# Congratulations!

You've just proven the **Rearrangement Theorem**—one of the crown jewels of real analysis!

## What We've Accomplished

This theorem completely characterizes when infinite summation is commutative. For absolutely convergent series, we can reorder terms with complete freedom—the sum is invariant. This is a profound result that took mathematicians centuries to fully understand and prove rigorously.

## The Proof: A Symphony of Ideas

The proof beautifully orchestrated all the machinery we've built:
- **Strong Cauchy property (Level 1)**: Any scattered collection of large-index terms has negligible sum
- **Eventually covers property (Level 2)**: Rearrangements eventually capture all early terms
- **Clever decomposition**: We split the difference between rearranged and original sums into "covered" and "uncovered" parts

The covered part is close to the limit by convergence of the original series. The uncovered part consists only of large-index terms, which by strong Cauchy have negligible sum. Together: the rearranged series converges to the same limit!

## Historical Significance

This theorem was understood by Cauchy and Abel in the 1820s, during the period when mathematicians were establishing rigorous foundations for calculus. It marked a crucial distinction between finite and infinite operations.

The realization that *order matters* for infinite sums was shocking at first. But this theorem shows the situation is elegant: absolute convergence is exactly the dividing line between order-independent ("finite-like") and order-dependent behavior.

## A Complete Dichotomy

We now have half of a stunning dichotomy:
- **This level**: Absolute convergence → rearrangement invariance
- **Next level**: Conditional convergence → complete chaos (any sum is possible!)

Together, these theorems show that there's no middle ground. A series either has an order-independent sum, or its sum can be manipulated to be anything we want by choosing the right rearrangement.

## The Power of Absolute Convergence

This theorem explains why absolute convergence is so important throughout analysis:
- It's the condition needed for term-by-term integration and differentiation
- It's required for multiplying infinite series (Cauchy product)
- It guarantees that double sums can be computed in either order (Fubini's theorem)

Absolute convergence is the "gold standard" that makes infinite series behave like finite sums.

## What's Next?

In Level 4, we'll see the shocking flip side: Riemann's Rearrangement Theorem. For conditionally convergent series, rearrangements can make the sum equal to *any* real number. The contrast couldn't be more dramatic!
`,
};

export default level;
