// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L2Pset/L2Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L2Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L2Pset_2",
  statement: `:
   ∃ c d e, ∀ (x : ℝ),
   (1 + 3 * x / 2 + c * x ^ 2 + d * x ^ 3 + e * x ^ 4) ^ 2
   - (1 + x) ^ 3
    =
    x ^ 5 * (
      3/128 + (11 * x)/512 - (3 * x^2)/1024 + (9 * x^3)/16384
    )`,
  goal: "∃ c d e, ∀ (x : ℝ), (1 + 3 * x / 2 + c * x ^ 2 + d * x ^ 3 + e * x ^ 4) ^ 2 - (1 + x) ^ 3 = x ^ 5 * ( 3/128 + (11 * x)/512 - (3 * x^2)/1024 + (9 * x^3)/16384 )",
  introduction: `# Problem 2

Do the same for the exponent $3/2$. Find constants \`c\`, \`d\`, and \`e\` so that:

$(1 + \\frac32 x + c \\cdot x^2 + d \\cdot x^3 + e \\cdot x^4)^2 - (1 + x) ^ 3$

has only terms of degree five or higher.

Hint: when you have multiple existential quantifiers, you can just write a single \`use\`
and separate the answers by a comma, like so: \`use 6, 7, 42\` (in place of: \`use 6\`, then \`use 7\`, then \`use 42\`).

`,
  conclusion: "Done.",
};

export default level;
