// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L3Pset/L3Pset4.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L3Pset",
  level: 4,
  name: "Problem 4",
  theoremName: "L3Pset_4",
  statement: `(a : ℕ → ℝ) (ha : ∀ n, a n = (3 * n + 8) / (2 * n + 5)) :
    ∃ L, SeqLim a L`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ n, a n = (3 * n + 8) / (2 * n + 5))",
  goal: "∃ L, SeqLim a L",
  introduction: `# Problem 4

Here's an even more involved limit problem. We've had luck getting \`bound\` to prove \`|X| = X\`, especially when there's a hypothesis \`h : 0 ≤ X\` already available in the list of assumptions. But I've found it not to be reliable, unfortunately. So let me give you one more theorem for your toolchest.

## New Theorem: \`abs_of_nonneg\`.
If you have a hypothesis \`h : 0 ≤ X\` in your toolchest,
then you can prove that \`|X| = X\` via:

\`have factName : |X| = X := by apply abs_of_nonneg h\`.
`,
  conclusion: "Done.",
};

export default level;
