// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L3Pset/L3Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L3Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L3Pset_1",
  statement: "(x y : ℝ) (x_pos : 0 < x) (y_pos : 0 < y) : ∃ (N : ℕ), y < x * N",
  objects: "(x y : ℝ)",
  assumptions: "(x_pos : 0 < x) (y_pos : 0 < y)",
  goal: "∃ (N : ℕ), y < x * N",
  introduction: `# Problem 1

The "full" Archimedean Property is this:
Take two positive real numbers \`x\` and \`y\`. No matter
how large \`y\` may be, and how small \`x\` may be,
if we add \`x\` to itself enough times (that is, multiply it by some natural number), we can always get that to exceed \`y\`.
`,
  conclusion: "Done.",
};

export default level;
