// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L3Pset/L3Pset3.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L3Pset",
  level: 3,
  name: "Problem 3",
  theoremName: "L3Pset_3",
  statement: `(a : ℕ → ℝ) (ha : ∀ n, a n = 1 / n ^ 2) :
    ∃ L, SeqLim a L`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ n, a n = 1 / n ^ 2)",
  goal: "∃ L, SeqLim a L",
  introduction: `# Problem 3

Determine what the limit of the sequence \`1 / n ^ 2\` is, and prove it.

Hints you may find useful:
- We have yet to learn about dealing with the square-root function.
So see if you can be even lazier in your choice of parameters...
- If you know that \`h : 0 < N\` holds in the *natural* numbers, then you can prove that that \`1 ≤ N\` simply by \`apply\`ing \`h\`, that is: \`have h' : 1 ≤ N := by apply h\`. (This would not work for an inequality in the real numbers, since it's in general not true!)
`,
  conclusion: "Done.",
};

export default level;
