// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L3Pset/L3Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L3Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L3Pset_2",
  statement: `(a : ℕ → ℝ) (ha : ∀ n, a n = (n + 1) / n) :
    ∃ L, SeqLim a L`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ n, a n = (n + 1) / n)",
  goal: "∃ L, SeqLim a L",
  introduction: `# Problem 2

Prove that the sequence \`(n + 1) / n\` has a limit, say, \`L\`, and determine what it is.

We haven't yet learned a good way to use the theorem \`OneOverNLimZero\`
that we already proved, so just adapt the proof of that, rather than trying to quote it. (It's good practice!)
`,
  conclusion: "Done.",
};

export default level;
