// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L6Pset/L6Pset5.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L6Pset",
  level: 5,
  name: "Problem 5",
  theoremName: "L6Pset_5",
  statement: `(a b c d e : ℕ → ℝ) (L : ℝ)
(ha : SeqLim a L)
(hc : SeqLim c L)
(he : SeqLim e L)
(hab : ∀ n, a n ≤ b n)
(hbc : ∀ n, b n ≤ c n)
(hcd : ∀ n, c n ≤ d n)
(hde : ∀ n, d n ≤ e n)
  : SeqLim b L ∧ SeqLim d L`,
  objects: "(a b c d e : ℕ → ℝ) (L : ℝ)",
  assumptions: "(ha : SeqLim a L) (hc : SeqLim c L) (he : SeqLim e L) (hab : ∀ n, a n ≤ b n) (hbc : ∀ n, b n ≤ c n) (hcd : ∀ n, c n ≤ d n) (hde : ∀ n, d n ≤ e n)",
  goal: "SeqLim b L ∧ SeqLim d L",
  introduction: `# Problem 5

You are given five sequences \`a b c d e : ℕ → ℝ\`, and you know that
\`a\`, \`c\`, and \`e\` converge to \`L\`, and that, for all \`n\`, \`a n ≤ b n ≤ c n ≤ d n ≤ e n\`.
Prove that both \`b\` and \`d\` also converge to \`L\`.
`,
  conclusion: "Done. (Hopefully you didn't do that by hand, but rather quoted -- twice -- a theorem that we recently proved?)",
};

export default level;
