// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L6Pset/L6Pset3.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L6Pset",
  level: 3,
  name: "Problem 3",
  theoremName: "L6Pset_3",
  statement: `(a : ℕ → ℝ) (ha : SeqLim a 5)
  : ∃ N, ∀ n ≥ N, 0 < a n`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : SeqLim a 5)",
  goal: "∃ N, ∀ n ≥ N, 0 < a n",
  introduction: `# Problem 3

You are given that a sequence \`a : ℕ → ℝ\` converges to 5.
Prove that it is eventually positive.
`,
  conclusion: "Done.",
};

export default level;
