// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L6Pset/L6Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L6Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L6Pset_2",
  statement: `(x y z : ℝ) (h : x = 2 ∧ y = 3 ∧ z = 4)
  : z = 4`,
  objects: "(x y z : ℝ)",
  assumptions: "(h : x = 2 ∧ y = 3 ∧ z = 4)",
  goal: "z = 4",
  introduction: `# Problem 2

You know that \`h : x = 2 ∧ y = 3 ∧ z = 4\`.
Your goal is to show that: \`z = 4\`.
`,
  conclusion: "Done.",
};

export default level;
