// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L6Pset/L6Pset4.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L6Pset",
  level: 4,
  name: "Problem 4",
  theoremName: "L6Pset_4",
  statement: `(a : ℕ → ℝ) (ha : ∀ N, ∃ n ≥ N, |a n| > 10)
  : ¬ ∃ L, |L| < 5 ∧ SeqLim a L`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ N, ∃ n ≥ N, |a n| > 10)",
  goal: "¬ ∃ L, |L| < 5 ∧ SeqLim a L",
  introduction: `# Problem 4

You are given that a sequence \`a : ℕ → ℝ\` with the property that it takes arbitrarily large values exceeding 10 in absolute value.
Prove that cannot have a limit less than 5.
`,
  conclusion: "Done.",
};

export default level;
