// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L6Pset/L6Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L6Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L6Pset_1",
  statement: `(x y z : ℝ) (hx : x = 2) (hy : y = 3) (hz : z = 4)
  : x = 2 ∧ y = 3 ∧ z = 4`,
  objects: "(x y z : ℝ)",
  assumptions: "(hx : x = 2) (hy : y = 3) (hz : z = 4)",
  goal: "x = 2 ∧ y = 3 ∧ z = 4",
  introduction: `# Problem 1

You know that \`hx : x = 2\`, \`hy : y = 3\`, and that \`hz : z = 4\`.
Your goal is to show that: \`x = 2 ∧ y = 3 ∧ z = 4\`.
`,
  conclusion: "Done.",
};

export default level;
