// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L8Pset/L8Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L8Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L8Pset_1",
  statement: "(n : ℕ) : 2 * n + 9 ≤ 2 ^ (n + 4)",
  objects: "(n : ℕ)",
  goal: "2 * n + 9 ≤ 2 ^ (n + 4)",
  introduction: `# Problem 1

`,
  conclusion: "",
};

export default level;
