// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L8Pset/L8Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L8Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L8Pset_2",
  statement: ": ∃ N, ∀ n, (n + N) ^ 2 ≤ 2 ^ (n + N)",
  goal: "∃ N, ∀ n, (n + N) ^ 2 ≤ 2 ^ (n + N)",
  introduction: `# Problem 2

We proved in class that \`n < 2 ^ n\`. It's even true that \`n ^ 2 ≤ 2 ^ n\`, but only for \`n\` sufficiently large (how large?).

Look at the problem statement. Note how we've implemented induction starting somewhere other than zero: by shifting the argument by that amount.

Hint: The result from Problem 1 might come in handy...
`,
  conclusion: "",
};

export default level;
