// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L8Pset/L8Pset3.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L8Pset",
  level: 3,
  name: "Problem 3",
  theoremName: "L8Pset_3",
  statement: "(n : ℕ) : ∃ k, n * (n + 1) * (2 * n + 1) = 6 * k",
  objects: "(n : ℕ)",
  goal: "∃ k, n * (n + 1) * (2 * n + 1) = 6 * k",
  introduction: `# Problem 3

Prove that \`n (n + 1) (2 n + 1)\` is always divisible by \`6\`. (Hint: induction.)
`,
  conclusion: "",
};

export default level;
