// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L8Pset/L8Pset4.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L8Pset",
  level: 4,
  name: "Problem 4",
  theoremName: "L8Pset_4",
  statement: "SubseqGe {σ : ℕ → ℕ} (hσ : ∀ i j, i < j → σ (i) < σ (j)) : ∀ n, n ≤ σ (n)",
  objects: "{σ : ℕ → ℕ}",
  assumptions: "(hσ : ∀ i j, i < j → σ (i) < σ (j))",
  goal: "∀ n, n ≤ σ (n)",
  introduction: `# Problem 4

Suppose a sequence \`σ : ℕ → ℕ\` takes values in the
*natural numbers* (not reals), and is strictly increasing, that is,
if \`i < j\`, then \`σ (i) < σ (j)\`. Prove that
\`σ (n)\` grows at least as fast as \`n\` itself.

`,
  conclusion: "",
};

export default level;
