// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L10Pset/L10Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L10Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L10Pset_1",
  statement: `(a b c : ℕ → ℝ) (ha : SeqLim a 0) (hb : SeqBdd b) (hc : ∀ n, c n = a n * b n)
      : SeqLim c 0`,
  objects: "(a b c : ℕ → ℝ)",
  assumptions: "(ha : SeqLim a 0) (hb : SeqBdd b) (hc : ∀ n, c n = a n * b n)",
  goal: "SeqLim c 0",
  introduction: `
# Problem 1:


Prove the Theorem \`LimZeroTimesBdd\`: if a sequence \`a n\` converges to \`0\`, and the sequence \`b n\` is merely bounded (not necessarily convergent!), then the product
\`a * b\` converges to \`0\`.
`,
  conclusion: "Done.",
};

export default level;
