// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L10Pset/L10Pset4.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L10Pset",
  level: 3,
  name: "Problem 3",
  theoremName: "L10Pset_3",
  statement: `(a : ℕ → ℝ) (L : ℝ) (ha : SeqLim a L) (K : ℝ) (hK : ∀ n, K < a n) :
    K ≤ L`,
  objects: "(a : ℕ → ℝ) (L : ℝ) (K : ℝ)",
  assumptions: "(ha : SeqLim a L) (hK : ∀ n, K < a n)",
  goal: "K ≤ L",
  introduction: `
# Problem 3:

We proved \`OrderLimLe\`; now prove \`OrderLimGt\`. Notice that the assumption is a **strict** inequality, but the conclusion is not. Why not? (See next Exercise...)

`,
  conclusion: "Done.",
};

export default level;
