// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L10Pset/L10Pset5.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L10Pset",
  level: 4,
  name: "Problem 4",
  theoremName: "L10Pset_4",
  statement: ": ∃ a, SeqLim a 0 ∧ ∀ n, 0 < a n",
  goal: "∃ a, SeqLim a 0 ∧ ∀ n, 0 < a n",
  introduction: `
# Problem 4:

Exhibit (by starting with \`let a : ℕ → ℝ := fun n ↦ ???\`)
a sequence so that

- the terms are all strictly positive: \`∀ n, 0 < a n\`,
- and yet the sequence converges to zero (and not something strictly positive!).

When you define a new sequence using \`let\`, you might find it
convenient to immediately prove a trivial theorem restating the definition:

\`have ha : ∀ n, a n = ??? := by intro n; rfl\`

This may become useful should you want to \`rewrite\` by \`ha\` (you can't rewrite by \`a\`, since it's a definition, not a theorem!)...

**Extra challenge:** See if you can do it by using theorems we already proved, not by going into the \`ε-N\` definition...

`,
  conclusion: "Done.",
};

export default level;
