// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L10Pset/L10Pset1NOTUSED.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L10Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L10Pset_1",
  statement: `(a b c : ℕ → ℝ) (hc : ∀ n, c n = if Even n then a (n / 2) else b ((n - 1) / 2))
        (cConv : SeqConv c) : ∃ L, SeqLim a L`,
  objects: "(a b c : ℕ → ℝ)",
  assumptions: "(hc : ∀ n, c n = if Even n then a (n / 2) else b ((n - 1) / 2)) (cConv : SeqConv c)",
  goal: "∃ L, SeqLim a L",
  introduction: `
# Problem 1:

Assume that the sequence \`c\` is a shuffling of sequences \`a\` and \`b\`,
namely, that \`(c 0, c 1, c 2, ...) = (a 0, b 0, a 1, b 1, a 2, b 2,...)\`.
Assume that the sequence \`c\` converges.
Prove that the sequences \`a\` and \`b\` converge, and to the same thing. It's enough to prove that \`a\` converges, as the proof for \`b\` will be similar.

## New tactic! \`grind\`

We'll add another powerful tactic that sometimes works where \`bound\` doesn't; it's called \`grind\`.

In this exercise, you might find it useful at some point to write:

\`have fact : (if Even (2 * n) then a (2 * n / 2) else b ((2 * n - 1) / 2)) = a n := by grind\`

On the right of this equality is just \`a n\`; on the left it says: if \`2 * n\` is \`Even\` (which of course it is), then return \`a (2 * n / 2)\` -- which we want \`grind\` to simplify to \`a n\` -- and if not, then return \`b ((2n-1)/2)\` -- which is irrelevant, since \`2n\` is not odd.

See if you can solve it from there...
`,
  conclusion: "Done.",
};

export default level;
