// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L10Pset/L10Pset3.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L10Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L10Pset_2",
  statement: `(a b c : ℕ → ℝ) (L M : ℝ) (ha : SeqLim a L)
    (hb : SeqLim b M) (hc : ∀ n, c n = a n * b n):
    SeqLim c (L * M)`,
  objects: "(a b c : ℕ → ℝ) (L M : ℝ)",
  assumptions: "(ha : SeqLim a L) (hb : SeqLim b M) (hc : ∀ n, c n = a n * b n)",
  goal: "SeqLim c (L * M)",
  introduction: `
# Problem 2:

Finish the proof of \`ProdLim\`.

`,
  conclusion: "Done.",
};

export default level;
