// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L10Pset/L10Pset7.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L10Pset",
  level: 6,
  name: "Problem 6",
  theoremName: "L10Pset_6",
  statement: `(a : ℕ → ℝ) (σ τ : ℕ → ℕ)
    (σsub : Subseq σ) (τsub : Subseq τ) (L M : ℝ)
    (hσ : SeqLim (a ∘ σ) L) (hτ : SeqLim (a ∘ τ) M) (hLM : L ≠ M)
    : ¬ SeqConv a`,
  objects: "(a : ℕ → ℝ) (σ τ : ℕ → ℕ) (σsub : Subseq σ) (τsub : Subseq τ) (L M : ℝ)",
  assumptions: "(hσ : SeqLim (a ∘ σ) L) (hτ : SeqLim (a ∘ τ) M) (hLM : L ≠ M)",
  goal: "¬ SeqConv a",
  introduction: `
# Problem 6:

Show that if a sequence has two subsequences that converge to
different limits, then the sequence itself cannot converge.

`,
  conclusion: "Done.",
};

export default level;
