// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L10Pset/L10Pset6.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L10Pset",
  level: 5,
  name: "Problem 5",
  theoremName: "L10Pset_5",
  statement: "(a : ℕ → ℝ) (ha : ∀ n, a n = n) : ¬ SeqBdd a",
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ n, a n = n)",
  goal: "¬ SeqBdd a",
  introduction: `
# Problem 5:

Show that the sequence \`a n = n\` is unbounded.

`,
  conclusion: "Done.",
};

export default level;
