// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L12Pset/L12Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L12Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L12Pset_1",
  statement: `{X : Type*} [NormedField X] [LinearOrder X] [IsStrictOrderedRing X] [FloorSemiring X]
    {a : ℕ → X} {M : X} (ha : Antitone a) (hM : ∀ n, M ≤ a n)
    : IsCauchy a`,
  objects: "{X : Type*} [NormedField X] [LinearOrder X] [IsStrictOrderedRing X] [FloorSemiring X] {a : ℕ → X} {M : X}",
  assumptions: "(ha : Antitone a) (hM : ∀ n, M ≤ a n)",
  goal: "IsCauchy a",
  introduction: `
# Problem 1:

In lecture, we proved \`IsCauchy_of_MonotoneBdd\`: if a sequence is \`Monotone\` and bounded (from above),
then it \`IsCauchy\`. Here you'll prove the same thing but going down: if a sequence is \`Antitone\` (that
is, non-increasing -- so decreasing but not necessarily strictly so; \`i ≤ j → a j ≤ a i) and bounded
from *below*, then it's Cauchy.

Theorem: \`IsCauchy_of_AntitoneBdd\`.

## New definition: \`Antitone\`

Hint: You don't need to reprove everything from scratch! I'll give you two tools:

## New theorems:

- \`MonotoneNeg_of_Antitone\`: if \`a\` is \`Antitone\`, then \`-a\` is \`Monotone\`.

- \`IsCauchyNeg\`: if \`IsCauchy a\`, then so is \`IsCauchy (-a)\`.

`,
  conclusion: "",
};

export default level;
