// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L12Pset/L12Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L12Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L12Pset_2",
  statement: "(a : ℕ → ℝ) (ha : ∀ n, a n = 1 / n) : IsCauchy a ∧ ¬ Monotone a ∧ ¬ Antitone a",
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ n, a n = 1 / n)",
  goal: "IsCauchy a ∧ ¬ Monotone a ∧ ¬ Antitone a",
  introduction: `
# Problem 2:

More fun with Cauchy sequences. Show that \`1/n\` is Cauchy but is neither \`Monotone\` nor \`Antitone\`! (Because of how division by zero works in Lean...)

`,
  conclusion: "",
};

export default level;
