// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L9Levels/L04_FiniteSums.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture9",
  level: 1,
  name: "Finite Sums",
  theoremName: "Lecture9_1",
  statement: `TermLeSum {X : Type*} [NormedField X] [LinearOrder X] [IsStrictOrderedRing X] (a : ℕ → X) (N : ℕ) :
    ∀ n < N, |a n| ≤ ∑ k ∈ range N, |a k|`,
  objects: "{X : Type*} [NormedField X] [LinearOrder X] [IsStrictOrderedRing X] (a : ℕ → X) (N : ℕ)",
  goal: "∀ n < N, |a n| ≤ ∑ k ∈ range N, |a k|",
  introduction: `
# Level 1: Finite Sums

Welcome to a new world of mathematics: **finite sums**! In this level, you'll prove that any individual term in a sum of absolute values is bounded by the total sum. This is a fundamental property that bridges discrete and continuous mathematics.

## The Goal

Prove that for any sequence \`a : ℕ → ℝ\` and natural number \`N\`, every term \`|a n|\` with \`n < N\` is at most the sum \`∑ k ∈ range N, |a k|\`.

Intuitively: if you're adding up a bunch of nonnegative numbers, no single number can be bigger than the total!

## Strategy: Induction from the Start!

🎯 **Big Hint:** Even though the goal starts with \`∀ n < N\`, do **NOT** begin with \`intro n hn\`. Instead, run **induction on \`N\`** right from the beginning!

This might feel counterintuitive, but trust the process. Induction gives you the perfect structure to peel off one term at a time using \`sum_range_succ\`.

### Your Induction Strategy:
- **Base case (\`N = 0\`):** There are no natural numbers less than 0, so you'll get a \`contradiction\`
- **Inductive step (\`N → N + 1\`):** Use \`sum_range_succ\` to write the sum for \`N + 1\` as the sum for \`N\` plus the new term \`|a N|\`
  - Split into cases: Is \`n < N\` (use inductive hypothesis) or \`n = N\` (use nonnegativity)?

## New Tools You'll Need

### Summation Notation
\`∑ k ∈ range N\` means sum as \`k\` goes from \`0\` to \`N - 1\` (which has \`N\` terms total!)

### \`sum_range_succ\`
Peels off the last term: \`∑ k ∈ range (N + 1), f k = (∑ k ∈ range N, f k) + f N\`

### \`sum_nonneg\`
If each term is nonnegative, so is the sum. Usage: \`apply sum_nonneg\`, then prove \`∀ k ∈ range N, 0 ≤ f k\`

### \`contradiction\`
If your hypotheses are contradictory (like \`n : ℕ\` with \`n < 0\`), this tactic closes the goal immediately.

### \`by_cases\`
Split into cases based on a decidable proposition. Usage: \`by_cases h : n < N\` creates two goals:
- One where \`h : n < N\` holds
- One where \`h : ¬(n < N)\` holds

Good luck! Remember: **induction first, then introduce \`n\`!**
`,
  conclusion: `
# 🎉 Excellent Work!

You've just proven a fundamental result about finite sums! This theorem might seem simple, but it's a powerful building block that appears throughout analysis.

## What You Accomplished

You successfully proved that **every term is bounded by the total sum**:
\`\`\`
∀ n < N, |a n| ≤ ∑ k ∈ range N, |a k|
\`\`\`

### Key Techniques You Mastered:

1. **Strategic induction** - You learned to use induction on \`N\` *before* introducing the universal quantifier, which made the proof structure much cleaner

2. **Working with finite sums** - You used \`sum_range_succ\` to peel off terms and \`sum_nonneg\` to establish nonnegativity

3. **Case analysis** - You split the proof into two cases (\`n < N\` vs \`n = N\`) and handled each appropriately

4. **Combining results** - You cleverly used the inductive hypothesis for earlier terms and nonnegativity for the final term

## Why This Matters

This result is essential for the next level! You'll use \`TermLeSum\` to prove that **convergent sequences are bounded**. Here's the connection:

- Every convergent sequence is eventually close to its limit
- But what about the finitely many terms *before* it gets close?
- That's where your theorem comes in! You can bound those initial terms by their finite sum
- Combine this with the eventual bound, and you get a global bound for the entire sequence

## Looking Ahead

In the next level, you'll prove \`Bdd_of_ConvNonzero\`: convergent sequences with nonzero limits are bounded. This is a cornerstone result in analysis that tells us convergent sequences can't escape to infinity.

Ready to see your theorem in action? Let's move on!
`,
};

export default level;
