// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L9Levels/L05_BddOfConv.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture9",
  level: 2,
  name: "Bounded",
  theoremName: "Lecture9_2",
  statement: `(a : ℕ → ℝ) (L : ℝ) (ha : SeqLim a L) (hL : L ≠ 0) :
    SeqBdd a`,
  objects: "(a : ℕ → ℝ) (L : ℝ)",
  assumptions: "(ha : SeqLim a L) (hL : L ≠ 0)",
  goal: "SeqBdd a",
  introduction: `
# Level 2: Bounded

Welcome to one of the most fundamental results in real analysis: **convergent sequences are bounded**! This theorem tells us that if a sequence converges to a limit, it can't wander off to infinity—it must stay within some finite region.

## The Goal

Prove that if \`a : ℕ → ℝ\` converges to a nonzero limit \`L\`, then \`a\` is bounded (i.e., there exists some \`M > 0\` such that \`|a n| ≤ M\` for all \`n\`).

**Note:** The case \`L = 0\` will be handled in the exercises. For now, we focus on nonzero limits.

## The Big Idea

Think about what convergence means: eventually, all terms get close to \`L\`. So for large \`n\`, we have \`|a n| ≤ 2|L|\` (approximately).

But what about the **finitely many terms before** the sequence gets close to \`L\`? That's where your \`TermLeSum\` theorem from Level 1 comes in! You can bound those initial terms by their finite sum.

### The Strategy:

1. **Eventually bounded:** Use \`EventuallyBdd_of_SeqConv\` to find an \`N\` such that \`|a n| ≤ 2|L|\` for all \`n ≥ N\`

2. **Initially bounded:** For \`n < N\`, use \`TermLeSum\` to show \`|a n| ≤ ∑ k ∈ range N, |a k|\`

3. **Global bound:** Combine both parts with:
   \`\`\`
   M = 2 * |L| + ∑ k ∈ range N, |a k|
   \`\`\`

   This works because:
   - For \`n ≥ N\`: the term \`|a n|\` is covered by \`2|L|\`
   - For \`n < N\`: the term \`|a n|\` is covered by the sum

4. **Prove \`M > 0\`:** Show that your bound is positive (needed for the definition of \`SeqBdd\`)

5. **Prove \`∀ n, |a n| ≤ M\`:** Split into cases based on whether \`n ≥ N\` or \`n < N\`

## New Tools You'll Need

### \`SeqBdd\`
Definition: A sequence \`a : ℕ → ℝ\` is **bounded** if \`∃ M > 0, ∀ n, |a n| ≤ M\`

## Your Mission

Construct the bound \`M\`, prove it's positive, then verify it works for all terms by splitting into the two cases. Let your \`TermLeSum\` theorem shine!

Good luck! 🚀
`,
  conclusion: `
# 🎉 Outstanding Achievement!

You've just proven one of the **cornerstone theorems of real analysis**: convergent sequences with nonzero limits are bounded! This is a result you'll use again and again throughout your journey in analysis.

## What You Accomplished

You proved that convergence implies boundedness:
\`\`\`
SeqLim a L → L ≠ 0 → SeqBdd a
\`\`\`

This tells us something profound: **convergent sequences can't escape to infinity**. They must remain trapped in a finite region of the real line.

### Key Techniques You Mastered:

1. **Two-region strategy** - You split the natural numbers into two parts:
   - Eventually (n ≥ N): where convergence gives you control
   - Initially (n < N): where you used your TermLtSum theorem

2. **Constructing clever bounds** - You built \`M = 2*|L| + ∑ k ∈ range N, |a k|\`, which elegantly captures both regions in a single expression

3. **Case analysis** - You used \`by_cases\` to handle the two regions separately, applying the appropriate bound for each

4. **Connecting theorems** - You saw how \`TermLtSum\` from Level 1 became an essential tool for handling finitely many terms

## Why This Matters

The boundedness of convergent sequences is fundamental throughout mathematics:

- **Bolzano-Weierstrass Theorem**: Every bounded sequence has a convergent subsequence (you've proven half of this!)
- **Uniform Convergence**: Bounded sequences are essential for proving uniform convergence results
- **Compactness**: This result is key to understanding compactness in metric spaces
- **Practical Analysis**: Knowing a sequence stays bounded helps with error analysis and numerical computations

## The Missing Piece: L = 0

Notice we assumed \`L ≠ 0\` in this proof. The case where \`L = 0\` is left as an exercise, but the idea is similar:
- Use convergence with \`ε = 1\` to bound terms eventually by \`1\`
- Handle the finitely many initial terms with TermLtSum
- The bound becomes \`M = 1 + ∑ k ∈ range N, |a k|\`

## Looking Ahead

You now understand that convergent sequences live in a bounded world. This prepares you for deeper results:
- Sequences that are bounded but don't converge (like \`(-1)^n\`)
- The relationship between boundedness, monotonicity, and convergence
- Cauchy sequences and completeness of the reals

Congratulations on mastering this essential theorem! You're building the foundation for advanced analysis. Keep going! 🚀
`,
};

export default level;
