// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1RealAnalysisStory/L00_the_problem.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "RealAnalysisStory",
  level: 1,
  name: "Introduction to Lean",
  theoremName: "RealAnalysisStory_1",
  theoremBlockLabel: "Example",
  showTheoremName: false,
  statement: "(x : ℝ) (h : x = 5) : x = 5",
  objects: "(x : ℝ)",
  assumptions: "(h : x = 5)",
  goal: "x = 5",
  permissions: [
    {t: "allowTactic", tacticName: "prop"},
    {t: "allowTactic", tacticName: "tactic_apply"},
  ],
  introduction: `
# Theorem Prover Software

In this course, we will be using a "proof assistant" called Lean. This is software that checks that our proofs prove *exactly* what we
claim they prove. It has other really cool pedagogical features that we'll get to later.
It will take a little while to get used to the syntax, so until we're comfortable, we'll intersperse exercises teaching Lean with exercises teaching Real Analysis. Pretty soon all the exercises will just be about Real Analysis.


For this first exercise, we have a hypothesis that we called \`h\` (but we could've called it anything, like \`x_eq_5\`, or \`Alice\`) that says a real number \`x\` equals 5. Our goal is to prove that \`x\` equals 5.
This shouldn't be very hard, but if you don't know
the command, you'll be out of luck. Our goal is to
prove the same statement as one of the hypotheses.
To solve that goal, the syntax is to write \`apply\`, then a space, and then the name of the hypothesis which matches the goal.
`,
  tutorial: [
    {
      target: ".tutorial-workspace-anchor",
      spotlightTarget: ".blocklySvg",
      title: "Welcome to Formal Theorem Proving with Blocks!",
      content: "In this Game, every Level is an Escape Room: you move on when you’ve solved the Goal. Some will be easier than others. In this Tutorial World, we’ll learn the basic language of formal theorem proving. This open workspace is called the Field. You’ll drag Tactic Blocks here, fill them with Objects and Assumptions, and then snap the completed blocks into the Main Block to build your proof. Let’s get started!",
      placement: "bottom",
      offset: -50,
    },
    {
      target: ".tutorial-theorem-block",
      title: "Read the Statement",
      content: "The Main Block tells you what you're trying to prove, whether it's a named Theorem or just an Example. In this particular Level, you are given a real number $x$, and an assumption, called `h`, that $x = 5$. Your Goal is to prove that $x = 5$. Yes, you read that right; this can't be too hard. But how exactly do you do it? Let's see.",
      placement: "bottom",
    },
    {
      target: ".goals-panel",
      title: "Watch the Game Board",
      content: "The Game Board on the right shows your current Proof State. At the start, it matches the Main Block: the same Objects, Assumptions, and Goal. As the game progresses, you’ll add ever more complicated \"Tactic Blocks\" to the Main Block, and the Game Board will update after each move. Think of the analogy to chess: the Main Block records moves, like algebraic notation, `1. e4 e5 2. Nf3 Nf6`; meanwhile, the Game Board shows the actual positions those moves create. You’ll soon get most of your information from the Game Board.",
      placement: "left",
    },
    {
      target: ".tutorial-tactics-category-label",
      title: "Find your Tactics",
      content: "Your Tactic Blocks live on the left. Click `Tactics` to open the Tactic Palette. This tutorial will continue once the tab is open.",
      placement: "right",
      advanceOn: {
        kind: "elementExists",
        selector: ".blocklyFlyout [data-id=\"tutorial-toolbox-apply\"]",
        visible: true,
      },
      advanceDelayMs: 900,
    },
    {
      target: ".blocklyFlyout [data-id=\"tutorial-toolbox-apply\"]",
      title: "Drag apply into the Field",
      content: "Drag `apply` out into the middle of the workspace, but don't snap it into the Main Block yet. First we'll fill in what apply should use. The tutorial will continue once `apply` is on the Field.",
      placement: "right",
      targetWaitTimeout: 5000,
      skipScroll: true,
      openToolboxCategory: "Tactics",
      advanceOn: {
        kind: "workspaceHasBlock",
        block: { type: "tactic_apply" },
      },
    },
    {
      target: ".tutorial-hyp-h",
      title: "Drag out h",
      content: "On the Game Board, find the assumption named h. Drag just the name h into the empty slot on the apply block. The tutorial will continue once apply contains h.",
      placement: "left",
      advanceOn: {
        kind: "workspaceHasBlock",
        block: {
          type: "tactic_apply",
          inputs: {
            ARG: {
              type: "prop",
              fields: { PROP_NAME: "h" },
            },
          },
        },
      },
    },
    {
      target: ".tutorial-workspace-anchor",
      spotlightTarget: ".game-area",
      title: "Snap the proof together",
      content: "Now snap the completed apply h block into the proof area inside the theorem block. That tells Lean to prove the goal using the matching assumption h.",
      placement: "bottom",
      advanceOn: {
        kind: "workspaceHasBlock",
        location: "theoremProof",
        block: {
          type: "tactic_apply",
          inputs: {
            ARG: {
              type: "prop",
              fields: { PROP_NAME: "h" },
            },
          },
        },
      },
    },
    {
      target: ".proof-status",
      title: "Check your proof",
      content: "Lean is checking your blocks. When they prove the theorem, this status turns green and the tutorial will continue.",
      placement: "left",
      advanceOn: { kind: "proofComplete" },
    },
    {
      target: ".navbar-info-btn",
      content: "The Info button reopens the lesson text for this level.",
      placement: "bottom",
    },
    {
      target: ".navbar-reset-btn",
      content: "Reset level clears this workspace and puts the theorem back at the start.",
      placement: "bottom",
    },
    {
      target: ".navbar-tutorial-btn",
      content: "The question mark starts this tutorial again.",
      placement: "bottom",
    },
    {
      target: ".navbar-back-btn",
      content: "Back returns to the world map.",
      placement: "bottom",
    },
  ],
  conclusion: `
Perfect! You've completed your first Lean proof involving real numbers.

Remember: the \`apply\` tactic is used when you have what you need to prove the goal. Look at the top right: your list of tactics now includes \`apply\`, and if you forget how it works or what it does, just click on it for a reminder.
`,
};

export default level;
