// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1RealAnalysisStory/L00_the_problem.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "RealAnalysisStory",
  level: 1,
  name: "The “apply” Tactic",
  theoremName: "RealAnalysisStory_1",
  theoremBlockLabel: "Example",
  statement: "(x : ℝ) (h : x = 5) : x = 5",
  objects: "x : ℝ",
  assumptions: "h : x = 5",
  goal: "x = 5",
  permissions: [
    {t: "allowTactic", tacticName: "prop"},
    {t: "allowTactic", tacticName: "tactic_apply"},
  ],
  introduction: `
# Your First Formal Proof

In this Tutorial World, we are learning how to build formal proofs with blocks. This first level is deliberately tiny. You are given a real number \`x\` and an assumption, called \`h\` (but we could have called it just about anything, like \`Alice\`), that \`x = 5\`. Your Goal is to prove this same fact, that \`x = 5\`.

In ordinary mathematical writing, we might say: “This follows immediately from the assumption.” In this Game, we refer to assumptions by name. The tactic for "this follows immediately" is called \`apply\`.

So the formal proof is simply:

\`apply h\`
`,
  conclusion: `
Perfect! You've completed your first Lean proof involving real numbers.

Remember: the \`apply\` tactic is used when you have what you need to prove the goal. Look at the top right: your list of tactics now includes \`apply\`, and if you forget how it works or what it does, just click on it for a reminder.
`,
};

export default level;
