// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1RealAnalysisStory/L02_rfl.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "RealAnalysisStory",
  level: 2,
  name: "The rfl tactic",
  theoremName: "RealAnalysisStory_2",
  statement: "(x y : ℝ) : x ^ 2 + 2 * y = x ^ 2 + 2 * y",
  objects: "(x y : ℝ)",
  goal: "x ^ 2 + 2 * y = x ^ 2 + 2 * y",
  permissions: [
    {t: "allowTactic", tacticName: "prop"},
    {t: "allowTactic", tacticName: "tactic_apply"},
    {t: "allowTactic", tacticName: "tactic_refl"},
  ],
  introduction: `
# When things are identical to themselves

Sometimes in mathematics, we need to prove that something equals itself. For example, we might need to prove that $x ^ 2 + 2 * y = x ^ 2 + 2 * y$.

This isn't quite the same as our previous exercise. There, we had a hypothesis \`h\` that told us \`x = 5\`, and we used \`apply h\` to prove the goal \`x = 5\`.

But now we don't have any hypothesis that says \`x ^ 2 + 2 * y = x ^ 2 + 2 * y\`. We're just being asked to prove that some expression equals itself. We can't say \`apply something\` because there's no \`something\`.

Instead, we will use what mathematicians call the *reflexive property* of equality: everything is equal to itself. In Lean, if you get to a situation where you're trying to prove an equality, and the two things on both sides are *identical*, then the syntax is to give the command \`rfl\` (short for "reflexivity").

Try it out!
`,
  tutorial: [
    {
      target: ".goals-panel",
      content: "Look at the goal: the left side and right side are exactly the same expression.",
      placement: "left",
    },
    {
      target: ".blocklyToolbox",
      content: "For a goal where something equals itself, use the rfl tactic. Drag rfl into the theorem block.",
      placement: "right",
    },
    {
      target: ".proof-status",
      content: "Once rfl is in place, Lean should recognize the proof as complete.",
      placement: "left",
    },
  ],
  conclusion: `
Excellent! You've learned the \`rfl\` tactic.

The key difference:
- Use \`apply hypothesis_name\` when you have a hypothesis that matches your goal
- Use \`rfl\` when you need to prove that something equals itself

These are two of the most fundamental tactics in Lean. As we progress through real analysis, you'll see that many complex proofs ultimately come down to showing that two expressions are identical.
`,
};

export default level;
