// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1RealAnalysisStory/L03_rw.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "RealAnalysisStory",
  level: 3,
  name: "The `rewrite` tactic",
  theoremName: "RealAnalysisStory_3",
  statement: "(x y : ℝ) (Bob : x = 2) : x + y = 2 + y",
  objects: "(x y : ℝ)",
  assumptions: "(Bob : x = 2)",
  goal: "x + y = 2 + y",
  permissions: [
    {t: "allowTactic", tacticName: "prop"},
    {t: "allowTactic", tacticName: "tactic_apply"},
    {t: "allowTactic", tacticName: "tactic_refl"},
    {t: "allowTactic", tacticName: "tactic_rewrite"},
  ],
  introduction: `
# Rewriting with equalities

Now let's learn about rewriting. Suppose you have a hypothesis called \`Bob : x = 2\`, and your goal is to prove that \`x + y = 2 + y\`.

Can you use \`rfl\`? No, because the two sides of the goal (\`x + y\` and \`2 + y\`) are not *identically* the same.

Can you use \`apply Bob\`? No, because \`Bob\` says \`x = 2\`, which is not what the goal is asking for.

But you can use the hypothesis \`Bob\` to *rewrite* the goal. Since \`Bob\` tells us that \`x = 2\`, we can replace \`x\` with \`2\` in our goal.

In Lean, if you have a hypothesis which is an equality, and you want to replace the *left hand side* of that equality with the *right hand side* in your goal, you use the \`rewrite\` tactic. The syntax is:

\`rewrite [hypothesis_name]\`

Unfortunately, those square brackets are part of the Lean syntax, and there's nothing you or I can do about them right now. Just remember: \`rewrite [Bob]\` means "use the equality in \`Bob\` to rewrite the goal."

After you rewrite, you're not done. But you should know how to finish from there.

Try it out!
`,
  conclusion: `
Great! You've learned the \`rewrite\` tactic.

Notice what happened: after you typed \`rewrite [Bob]\`, the goal changed from \`x + y = 2 + y\` to \`2 + y = 2 + y\`. Then you needed to type \`rfl\` to finish the proof, since both sides were now identical.

So far you've learned:
- \`apply hypothesis_name\` when a hypothesis matches your goal
- \`rfl\` when you need to prove something equals itself
- \`rewrite [hypothesis_name]\` when you want to use an equality to rewrite your goal

The \`rewrite\` tactic is incredibly powerful and you'll use it constantly in real analysis!
`,
};

export default level;
