// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1RealAnalysisStory/L08_choose.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "RealAnalysisStory",
  level: 8,
  name: "The choose tactic",
  theoremName: "RealAnalysisStory_8",
  statement: "(f : ℝ → ℝ) (h : ∃ c : ℝ, f c = 2) : ∃ x : ℝ, (f x) ^ 2 = 4",
  objects: "(f : ℝ → ℝ)",
  assumptions: "(h : ∃ c : ℝ, f c = 2)",
  goal: "∃ x : ℝ, (f x) ^ 2 = 4",
  permissions: [
    {t: "allowTactic", tacticName: "prop"},
    {t: "allowTactic", tacticName: "tactic_apply"},
    {t: "allowTactic", tacticName: "tactic_refl"},
    {t: "allowTactic", tacticName: "tactic_rewrite"},
    {t: "allowTactic", tacticName: "tactic_ring_nf"},
    {t: "allowTactic", tacticName: "tactic_use"},
    {t: "allowTactic", tacticName: "tactic_intro"},
    {t: "allowTactic", tacticName: "tactic_specialize"},
    {t: "allowTactic", tacticName: "tactic_choose"},
    {t: "allowAllAffordances"},
  ],
  introduction: `
# Extracting information from existential quantifiers

Now let's learn the counterpart to \`use\`. You know that if you have \`∃\` in the goal, you write \`use\` to provide a specific value.

But suppose you have a *hypothesis* that says "there exists a real number \`c\` such that \`f (c) = 2\`". In Lean, this looks like:
\`h : ∃ (c : ℝ), f c = 2\`

And say you want to prove that "there exists a real number \`c\` such that \`(f c)^2 = 4\`".

Again, you can't just say \`apply h\` because these are different statements.
If you know from \`h\` that at least one such \`c\` exists, how do you *choose* one?
 The name of this command is... \`choose\`.

The syntax for \`choose\` is as follows:

\`choose c hc using h\`.

You need to give a name to both the value of \`c\`, and to the hypothesis with which \`c\` is bundled. Here we named it \`hc\` (a hypothesis about \`c\`).

You should be able to figure out how to solve the goal from here.
`,
  conclusion: `
Excellent! You've learned the \`choose\` tactic for working with existence in hypotheses.

Notice the complete pattern:
1. \`choose c hc using h\` unpacked the hypothesis into a specific value \`c\` and proof \`hc : f c = 2\`
2. \`use c\` provided this same value as our witness for the goal
3. \`rewrite [hc]\` rewrote \`f c\` as \`2\` in the goal, changing it to \`2^2 = 4\`
4. \`ring_nf\` verified that \`2 ^ 2 = 4\`

The symmetry is beautiful:
- \`use\` when you have \`∃\` in the goal ("here's my specific example")
- \`choose\` when you have \`∃\` in a hypothesis ("let me unpack this existence claim")

This completes your basic logical toolkit! In real analysis, you'll use \`choose\` constantly when working with:
- Limit definitions ("given ε > 0, there exists δ > 0...")
- Intermediate Value Theorem ("there exists c such that f(c) = 0")
- Existence theorems throughout analysis

You're now ready to tackle real mathematical proofs!
`,
};

export default level;
