// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1RealAnalysisStory/L09_big_boss.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "RealAnalysisStory",
  level: 9,
  name: "Big Boss: The Ultimate Tactic Challenge",
  theoremName: "RealAnalysisStory_9",
  statement: `(f : ℝ → ℝ) (h_existential : ∃ (a : ℝ), f (a) = 3) (h_universal : ∀ x > 0, f (x + 1) = f (x) + 9) :
  ∃ (b : ℝ), ∀ y > 0, f (y + 1)^2 = (f (y) + (f b)^2)^2`,
  permissions: [
    {t: "allowTactic", tacticName: "prop"},
    {t: "allowTactic", tacticName: "tactic_apply"},
    {t: "allowTactic", tacticName: "tactic_refl"},
    {t: "allowTactic", tacticName: "tactic_rewrite"},
    {t: "allowTactic", tacticName: "tactic_ring_nf"},
    {t: "allowTactic", tacticName: "tactic_use"},
    {t: "allowTactic", tacticName: "tactic_intro"},
    {t: "allowTactic", tacticName: "tactic_specialize"},
    {t: "allowTactic", tacticName: "tactic_choose"},
    {t: "allowAllAffordances"},
  ],
  introduction: `
# The Final Challenge

Congratulations! You've learned many fundamental tactics for mathematical reasoning in Lean:
- \`apply hypothesisName\` for when a hypothesis matches the goal
- \`rfl\` for reflexivity (proving \`X = X\`)
- \`rewrite [hypothesisName]\` for rewriting using equalities
- \`ring_nf\` for algebraic manipulation
- \`use\` for providing witnesses to existence statements in goals
- \`intro\` for handling universal quantifiers in goals
- \`specialize\` for applying universal statements to specific values in hypotheses
- \`choose value hypothesisOnValue using ExistentialHypothesis\` for extracting information from existence statements in hypotheses

Here's a little "Universal/Existential Quantifier Cheat Sheet":

|           | ∀        | ∃      |
|-----------|----------|--------|
| **Goal**  | \`intro\`    | \`use\`    |
| **Hypothesis** | \`specialize\` | \`choose\` |

Now it's time for your first **Big Boss** - a problem that requires you to use almost ALL of these tactics in a single proof!

**Lecture 1 Big Boss**
Given a function \`f\` and information about its behavior, prove a complex statement that involves existence, universals, algebra, and rewriting.

This is what real mathematical proofs look like - a careful orchestration of multiple reasoning steps. You've got this! Use everything you've learned.

**Extra Challenge**
If you want to *really* challenge yourself, play this level "blind". Write the assumptions and goal down on paper, close the computer, solve it by hand, keeping track *in your mind* of what happens to the game board after each command, and only once you’ve worked it all out, open the computer and see if Lean accepts your solution.

Why do you think that this would this be a good thing to do?

In general, I hope your *goal* in taking this course is to make your "Real Analysis Brain Muscles" stronger. By the end, you should be *really good* at
solving Real Analysis problems on paper, where you don't have Lean showing
you the Goal State after every move.
More broadly, the purpose of learning to solve Real Analysis problems is to learn to *think*, clearly, precisely. Strengthening your ability to work with pen and paper (or just mentally) directly transfers to *any* other context where you're exploring ideas, wrestling with complicated arguments, or trying to communicate clearly to others.

An LLM could easily work through all these Lean levels by pattern matching and logical manipulation - just as you could solve multiplication problems by plugging them into a calculator instead of memorizing your times tables. But that completely defeats the purpose of the exercise, which is to rewire your brain and build mathematical intuition. It's like deciding that you want to bench press 200 pounds, loading up the bar, and then using a forklift to lift it for you while you stand underneath - you might have moved the weight, but you haven't gotten any stronger. The real value isn't in producing correct proofs, it's in the cognitive transformation that happens when you *struggle* through the reasoning yourself, building the mental pathways that let you see mathematical structure intuitively.
`,
  conclusion: `
# 🎉 VICTORY! 🎉

You've defeated the Big Boss and mastered all the fundamental tactics of mathematical reasoning!

**Let's see what you just accomplished:**

1. **\`choose a ha using h_existential\`** - Extracted the witness \`a\` and fact that \`f (a) = 3\` from the hypothesis
2. **\`use a\`** - Chose \`a\` as your witness for the existence statement in the goal
3. **\`intro y hy\`** - Handled the universal quantifier "for all y > 0" in the goal
4. **\`specialize h_universal y hy\`** - Applied the universal property to your specific value in the hypothesis
5. **\`rewrite [h_universal]\`** - Used the specialized fact to rewrite the goal
6. **\`rewrite [ha]\`** - Used the original fact that \`f (a) = 3\` to also rewrite the goal
7. **\`ring_nf\`** - Verified finally that \`(f y + 9) ^ 2 = (f y + 3 ^ 2) ^ 2\`

You've just completed a genuinely sophisticated mathematical argument! This kind of multi-step reasoning, combining existence statements, universal properties, and algebraic manipulation, is exactly what you'll encounter throughout real analysis.

**You are now ready to begin your journey to rigorous calculus!**

Welcome to the Introduction to Formal Real Analysis. 🎓

**Epilogue**

Before we continue with more Real Analysis and more Lean, let’s pause to note a few interesting things about working formally.
Using a theorem prover interactively is (I hope) tremendously fun and (I hope) leads to rapid gains, immediate feedback, and clarity of thought.

Imagine trying to learn chess by just reading through algebraic notation - 1.e4 e5 2.Nf3 Nf6 3.Bb5 a6 - sure, all the information is technically there, but isn't it so much easier to learn by actually looking at a chess board and seeing how the position changes after each move? In mathematics, it would be extraordinarily tedious to manually write on the blackboard the entire goal state after every move, keeping track of all the hypotheses and their relationships by hand. A theorem prover does this bookkeeping for you automatically, letting you focus on the mathematical content rather than the clerical work.

But! This is, as we've already noted, a double-edged sword. We still want to train our brains to "see" a mental model of the goal state evolving - good chess players can visualize many moves ahead precisely because they've learned to maintain multiple mental game boards simultaneously. But until you develop that skill, and even after you have it, there's immense value in being able to instantly generate the current "game board" of your proof state. The immediate feedback helps you understand the consequences of each logical move, building the very intuition that will eventually let you work more independently. It's the difference between learning to navigate by always checking your GPS versus eventually developing an internal sense of direction - both have their place, and the former helps develop the latter.
`,
};

export default level;
