// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L15Pset/L15Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L15Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L15Pset_1",
  statement: "(a b : ℕ → ℚ) (ha : ∀ n, a n = 1 - 1 / 2 ^ n) (hb : ∀ n, b n = 1) : ∀ ε > 0, ∃ N, ∀ n ≥ N, |a n - b n| < ε",
  objects: "(a b : ℕ → ℚ)",
  assumptions: "(ha : ∀ n, a n = 1 - 1 / 2 ^ n) (hb : ∀ n, b n = 1)",
  goal: "∀ ε > 0, ∃ N, ∀ n ≥ N, |a n - b n| < ε",
  introduction: `
# Problem 1:

Prove that $0.999... = 1.0000$. Better yet, let's do it in binary.
That is, you have two **rational** (Cauchy) sequences, \`a n = 1 - 1 / 2^n\` and \`b n = 1\`.
The two sequences are equivalent if \`a n - b n\` goes to zero, that is, if for all \`ε > 0, ∃ N, ∀ n ≥ N, |a n - b n| < ε\`.

Hint: In Lecture 8, we proved a theorem (now) called \`IdLeTwoPow\`...

`,
  conclusion: "Done.",
};

export default level;
