// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L16Levels/L01_check.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture16",
  level: 1,
  name: "Series",
  theoremName: "Lecture16_1",
  statement: "(a : ℕ → ℝ) (ha : SeriesConv a) : SeqLim a 0",
  objects: "(a : ℕ → ℝ) (ha : SeriesConv a)",
  goal: "SeqLim a 0",
  introduction: `
# Level 1: The Vanishing Term Test

Welcome to the study of infinite series! We now begin one of the most important topics in analysis.

Given a sequence \`a : ℕ → ℝ\`, we want to understand what it means to add up *all* its terms:
\`a 0 + a 1 + a 2 + a 3 + ...\`

Since we can't literally add infinitely many numbers, we instead look at the sequence of **partial sums**:

**Definition (Series):** \`Series (a : ℕ → ℝ) : ℕ → ℝ := fun n ↦ ∑ k ∈ range n, a k\`

So \`Series a n\` is the sum of the first \`n\` terms of \`a\`.

**Definition (SeriesConv):** A series **converges** if its sequence of partial sums converges:
\`SeriesConv (a : ℕ → ℝ) : Prop := SeqConv (Series a)\`

**Definition (SeriesLim):** If the series converges to \`L\`, we write:
\`SeriesLim (a : ℕ → ℝ) (L : ℝ) : Prop := SeqLim (Series a) L\`

---

Your challenge: Prove that **if a series converges, its terms must go to zero**.

This is sometimes called the **nth-term test for divergence**: if the terms don't vanish, the series can't possibly converge!

**Hint:** If the partial sums form a convergent (hence Cauchy) sequence, what can you say about consecutive partial sums? And what's the relationship between \`Series a (n+1)\` and \`Series a n\`?

**Warning:** The converse is FALSE! The harmonic series \`∑ 1/k\` has terms going to zero, but it diverges. So vanishing terms are *necessary* but not *sufficient* for convergence.
`,
  conclusion: `
Excellent! You've proven one of the most important necessary conditions for series convergence.

## What You've Shown

**Theorem (LimZero_of_SeriesConv):** If \`SeriesConv a\`, then \`SeqLim a 0\`.

In other words: *The terms of a convergent series must approach zero.*

## Why This Matters

This gives us a quick **divergence test**. To show a series diverges, you only need to check whether its terms go to zero. If they don't, the series definitely diverges!

**Examples of divergent series:**
- \`∑ 1\` diverges (terms stay at 1)
- \`∑ (-1)^k\` diverges (terms oscillate between ±1)
- \`∑ k/(k+1)\` diverges (terms approach 1, not 0)

## The Key Insight

Your proof used a beautiful idea: the difference between consecutive partial sums is exactly one term of the original sequence:

\`Series a (n+1) - Series a n = a n\`

Since convergent sequences are Cauchy, consecutive partial sums get arbitrarily close together. Therefore the terms \`a n\` must vanish!

## Critical Warning: The Converse Fails!

Be careful! It is **NOT** true that if \`SeqLim a 0\`, then \`SeriesConv a\`.

The classic counterexample is the **harmonic series**:
\`∑ 1/k = 1 + 1/2 + 1/3 + 1/4 + ...\`

Here \`1/k → 0\`, but the series diverges! The partial sums grow like \`log n\`.

So vanishing terms are *necessary* but not *sufficient* for convergence. To prove a series converges, we need additional tests (which we'll develop in future levels).

## Historical Note

This test was known to early mathematicians like Nicole Oresme (14th century) and Jakob Bernoulli (17th century). It was one of the first tools for distinguishing convergent from divergent series.

Oresme also proved the harmonic series diverges using a clever grouping argument, showing that the converse of this theorem fails -- a result that surprised many mathematicians at the time!

---

**Next:** We'll evaluate some explicit series, starting with the beautiful Leibniz series.
`,
};

export default level;
