// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L7Levels/L03_SeqInvLim.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture7",
  level: 4,
  name: "SeqInvLim",
  theoremName: "Lecture7_4",
  statement: `(a : ℕ → ℝ) (L : ℝ) (aToL : SeqLim a L) (LneZero : L ≠ 0) (b : ℕ →
ℝ) (bEqInva : ∀ n, b n = 1 / a n) :
    SeqLim b (1 / L)`,
  objects: "(a : ℕ → ℝ) (L : ℝ) (b : ℕ → ℝ)",
  assumptions: "(aToL : SeqLim a L) (LneZero : L ≠ 0) (bEqInva : ∀ n, b n = 1 / a n)",
  goal: "SeqLim b (1 / L)",
  introduction: `
# Level 4: Reciprocals of Convergent Sequences — Big Boss Level

One of the most important limit theorems concerns reciprocals: if a sequence converges to
a nonzero limit, then the sequence of reciprocals converges to the reciprocal of the limit.
This result is crucial for proving theorems about quotients and rational functions.

This is a **Big Boss level**—it will require you to synthesize multiple techniques you've
developed throughout this lecture: working with nonzero limits, manipulating complex
algebraic expressions, and carefully choosing your epsilon strategy.

## What We're Proving

**Theorem:** If \`a : ℕ → ℝ\` converges to \`L\` with \`L ≠ 0\`, and \`b : ℕ → ℝ\` is defined
by \`b n = 1 / a n\` for all \`n\`, then \`b\` converges to \`1 / L\`.

This is the most technically challenging proof in this lecture.

## New Tools You'll Need

### \`abs_div\`
For any real numbers \`x\` and \`y\` (with \`y ≠ 0\`), we have \`|x / y| = |x| / |y|\`.

### \`nonzero_of_abs_pos\`
If \`0 < |x|\`, then \`x ≠ 0\`.

## Hints

Think about what you've proven in the previous levels:
- How can you ensure that \`a n ≠ 0\` eventually, so the reciprocals are well-defined?
- What happens when you try to bound \`|1/a n - 1/L|\`? Can you get a common denominator?
- How should you choose your epsilon when applying the convergence of \`a\` to \`L\`?
- What role does the lower bound on \`|a n|\` play in controlling the reciprocals?

The key is finding the right epsilon and carefully managing the algebraic manipulations
involving fractions. You have all the tools you need—now it's time to put them together!
`,
  conclusion: `
## Congratulations, Big Boss Defeated!

You've just completed one of the most challenging proofs in elementary analysis! The
reciprocal limit theorem is a major milestone—you've proven that reciprocals preserve
convergence (when the limit is nonzero).

## What You Accomplished

This proof required you to orchestrate multiple sophisticated techniques:
- Using \`EventuallyGeHalfLim\` to ensure denominators stay bounded away from zero
- Choosing a carefully calibrated epsilon (\`ε · |L|² / 2\`) to make the algebra work
- Manipulating complex fractional expressions with common denominators
- Applying \`abs_div\` to separate absolute values across division
- Chaining together a sequence of inequalities to reach the final bound

Each step built on the previous levels, showing how mathematical proofs are constructed
from carefully assembled building blocks.

## Applications and Extensions

With this theorem in hand, you now have a complete toolkit for limits of **rational
functions**. Combined with earlier results on sums and products, you can now prove:

**If \`a n → L\` and \`c n → M\` with \`M ≠ 0\`, then \`a n / c n → L / M\`.**

The proof is straightforward: first show \`1/c n → 1/M\` using the reciprocal theorem you
just proved, then use the product theorem to show \`a n · (1/c n) → L · (1/M) = L/M\`.

This completes the fundamental arithmetic of limits: sums, products, and quotients. These
are the building blocks for analyzing limits of polynomials, rational functions, and much
more complex expressions throughout calculus and analysis.

## Mastery of Technique

The reciprocal theorem showcases a crucial lesson in mathematical proof: sometimes the
"right" epsilon isn't the obvious choice. The expression \`ε · |L|² / 2\` might seem
mysterious at first, but it's precisely engineered to make the final inequalities work out.
This kind of strategic thinking—working backwards from what you need to figure out what
you should assume—is at the heart of mathematical problem-solving.

You've now mastered the essential techniques for proving limit theorems. Well done!
`,
};

export default level;
