// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L21Levels/L05.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture21",
  level: 1,
  name: "Sequential Criterion for Limits (Backward Direction)",
  theoremName: "Lecture21_1",
  statement: `FunLim_of_SeqLim {f : ℝ → ℝ} {L c : ℝ}
    (h : ∀ x : ℕ → ℝ, (∀ n, x n ≠ c) → SeqLim x c → SeqLim (fun n ↦ f (x n)) L) :
    FunLimAt f L c`,
  objects: "{f : ℝ → ℝ} {L c : ℝ}",
  assumptions: "(h : ∀ x : ℕ → ℝ, (∀ n, x n ≠ c) → SeqLim x c → SeqLim (fun n ↦ f (x n)) L)",
  goal: "FunLimAt f L c",
  introduction: `
# Level 1: Sequential Criterion for Limits (Backward Direction)

Previously, we proved that function limits imply sequential limits. Now we prove the **converse**: if function values converge for *every* appropriate sequence, then the function has a limit!

## The Sequential Criterion (Backward Direction)

**Theorem:** Suppose that for *every* sequence \`(xₙ)\` with \`xₙ → c\` and \`xₙ ≠ c\`, we have \`f(xₙ) → L\`. Then \`FunLimAt f L c\`.

This says: if sequences **test** the limit and all tests pass, then the function limit exists!

## Why This Direction Is Harder

The forward direction was straightforward: we had \`δ\` from the function limit and used it directly.

For the backward direction, we use **proof by contradiction**:
- Assume \`FunLimAt f L c\` is false
- Then \`∃ ε > 0\` such that \`∀ δ > 0\`, \`∃ x\` with \`|x - c| < δ\`, \`x ≠ c\`, but \`|f(x) - L| ≥ ε\`
- We'll construct a **problematic sequence** by choosing such an \`x\` for each \`δ = 1/(n+1)\`
- This sequence converges to \`c\` but \`f(xₙ)\` does *not* converge to \`L\`, contradicting our hypothesis!

## The Proof Strategy

**Given:** \`∀ x : ℕ → ℝ, (∀ n, x n ≠ c) → SeqLim x c → SeqLim (fun n ↦ f (x n)) L\`

**Want:** \`FunLimAt f L c\`, i.e., \`∀ ε > 0, ∃ δ > 0, ∀ x ≠ c, |x - c| < δ → |f(x) - L| < ε\`

**Proof by contradiction:**
1. **Assume negation:** \`∃ ε > 0\` such that \`∀ δ > 0\`, the implication fails
2. **Extract witnesses:** Use \`choose\` to get \`ε\` and a function \`g\` that produces counterexamples
3. **Construct sequence:** Define \`xₙ = g(1/(n+1))\` with \`|xₙ - c| < 1/(n+1)\` and \`|f(xₙ) - L| ≥ ε\`
4. **Show convergence:** Prove \`xₙ → c\` (since \`|xₙ - c| < 1/(n+1) → 0\`)
5. **Apply hypothesis:** Get \`f(xₙ) → L\` from our assumption
6. **Derive contradiction:** This contradicts \`|f(xₙ) - L| ≥ ε > 0\`

## Your Challenge

Prove the backward direction of the sequential criterion:

\`(∀ x : ℕ → ℝ, (∀ n, x n ≠ c) → SeqLim x c → SeqLim (fun n ↦ f (x n)) L) → FunLimAt f L c\`

**Key tactics to use:**
- \`by_contra\` to assume the negation
- \`push_neg\` to simplify the negated statement
- \`choose\` to extract witnesses from existential statements
- The Archimedean property to handle \`1/(n+1) → 0\`

**Hint:** The trickiest part is proving that your constructed sequence \`xₙ\` actually converges to \`c\`. You'll need to use the Archimedean property to find \`N\` such that \`1/N < δ\`, then show that for \`n ≥ N\`, we have \`1/(n+1) ≤ δ\`.

`,
  conclusion: `
# Congratulations!

You've just proved one of the most powerful and elegant results connecting sequences and function limits!

## What You Accomplished

The **Sequential Criterion (Backward Direction)** establishes that:

*If every sequence test passes, then the function limit exists.*

This is remarkable because it gives us a **sequential characterization** of function limits. We can now think about function limits in two equivalent ways:
- **ε-δ definition:** Traditional analytical approach
- **Sequential approach:** Test with all possible sequences

## The Power of Proof by Contradiction

Your proof showcased a beautiful contradiction argument:
1. **Assume** the function limit doesn't exist
2. **Construct** a problematic sequence using the failure of the ε-δ definition
3. **Show** this sequence converges to \`c\` but \`f(xₙ)\` doesn't converge to \`L\`
4. **Contradiction!** This violates our sequential hypothesis

This technique - constructing counterexample sequences from ε-δ failures - is a fundamental tool in real analysis.

## Why This Matters

Combined with the forward direction, we now have:

**Sequential Criterion for Function Limits (Complete):**
\`FunLimAt f L c ↔ (∀ x : ℕ → ℝ, (∀ n, x n ≠ c) → SeqLim x c → SeqLim (fun n ↦ f (x n)) L)\`

This equivalence is incredibly useful because:
- Sometimes sequences are easier to work with than ε-δ arguments
- It connects the discrete world (sequences) with the continuous world (functions)
- It provides a bridge between different areas of analysis

## Looking Ahead

This sequential criterion will be essential for:
- Proving properties of continuous functions
- Understanding derivatives (coming up next!)
- Advanced topics like uniform convergence and compactness

You've mastered a fundamental tool that working mathematicians use regularly. Well done!

`,
};

export default level;
