// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L23Levels/L02.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture23",
  level: 2,
  name: "Integration Converges!",
  theoremName: "Lecture23_2",
  statement: `(f : ℝ → ℝ) (a b : ℝ) (hab : a < b) (hf : UnifContOn f (Icc a b)) :
    IntegrableOn f a b`,
  objects: "(f : ℝ → ℝ) (a b : ℝ) (hf : UnifContOn f (Icc a b))",
  assumptions: "(hab : a < b)",
  goal: "IntegrableOn f a b",
  introduction: `
# Level 2: Integration Converges!

**The Big Question**: We know that continuous functions *should* be integrable, but proving this rigorously is surprisingly subtle. The key insight is that we need *uniform* continuity, not just pointwise continuity.

**What We're Proving**: If \`f\` is uniformly continuous on \`[a,b]\`, then the sequence of Riemann sums \`{RiemannSum f a b n}\` converges as \`n → ∞\`. This means the integral exists!

**The Strategy**: We'll prove convergence by showing the Riemann sum sequence is Cauchy. For any \`ε > 0\`:
1. Use uniform continuity to get a \`δ\` that works everywhere on \`[a,b]\`
2. Choose \`N\` large enough so that partitions with \`≥ N\` subintervals are all fine enough
3. For any \`m, n ≥ N\`, compare \`RiemannSum f a b m\` and \`RiemannSum f a b n\` by using their common multiple \`m * n\` as an intermediate step
4. Apply your Level 1 theorem twice to bound the total error

**New Definition - Uniform Continuity**:

\`def UnifContOn (f : ℝ → ℝ) (S : Set ℝ) : Prop :=
  ∀ ε > 0, ∃ δ > 0, ∀ x ∈ S, ∀ y ∈ S, |x - y| < δ → |f x - f y| < ε\`

**Key Insight**: Notice the quantifier order! Unlike pointwise continuity where \`δ\` can depend on the specific point \`x\`, uniform continuity requires a single \`δ\` that works for *all* pairs of points simultaneously. This seemingly small change makes all the difference for integration theory.
`,
  conclusion: `
# A Major Milestone!

Congratulations! You've just proved one of the fundamental theorems of real analysis: **uniformly continuous functions are integrable**.

**What Makes This Proof Beautiful**:
- **The Cauchy Strategy**: Instead of guessing what the integral should be, we proved convergence by showing the Riemann sum sequence is Cauchy. This is a powerful technique that works even when you don't know the limit in advance.
- **The Common Multiple Trick**: The key insight was using \`m * n\` as an intermediate step to compare Riemann sums with \`m\` and \`n\` partitions. This transformed a seemingly difficult comparison into two applications of your Level 1 theorem.
- **The ε/2 Split**: Dividing the tolerance in half and applying the triangle inequality is a classic move in analysis that you'll see again and again.

**The Historical Context**: This result was crucial for putting Riemann's theory of integration on solid foundations. Riemann himself understood this intuitively, but the rigorous proof required careful attention to uniform continuity - a concept that wasn't fully formalized until later.

**What's Still Missing**: We've shown that *uniformly* continuous functions are integrable, but when is a continuous function *uniformly* continuous? The answer involves one of the most important concepts in mathematics: **compactness**.

**Looking Ahead**: In Level 3, we'll prove that continuous functions on compact sets (like closed intervals \`[a,b]\`) are automatically uniformly continuous. Combined with today's result, this will show that *every* continuous function on \`[a,b]\` is integrable - the foundation of calculus!

This is why topology matters for analysis: the 'right' topological framework (compactness) makes analytical problems (integration) much more tractable.
`,
};

export default level;
