// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L23Levels/L03.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture23",
  level: 3,
  name: "Compactness",
  theoremName: "Lecture23_3",
  statement: "(f : ℝ → ℝ) (hf : FunCont f) (S : Set ℝ) (hS : IsCompact S) : UnifContOn f S",
  objects: "(f : ℝ → ℝ) (S : Set ℝ)",
  assumptions: "(hf : FunCont f) (hS : IsCompact S)",
  goal: "UnifContOn f S",
  introduction: `
# Level 3: Compactness

**The Final Puzzle Piece**: We've shown that uniformly continuous functions are integrable. But when is a continuous function *uniformly* continuous? The beautiful answer involves one of mathematics' most elegant concepts: **compactness**.

**The Big Theorem**: Every continuous function on a compact set is automatically uniformly continuous on that set. Combined with Level 2, this means every continuous function on a compact set is integrable!

**What Is Compactness?**: Intuitively, a set is compact if it's "small enough" that any covering by open balls can be reduced to a finite covering. Here's the key insight for uniform continuity:

1. **Start with continuity**: At each point \`x\` in your set \`S\`, continuity gives you a ball around \`x\` where the function doesn't vary much
2. **Cover the set**: These balls cover your entire set \`S\`
3. **Apply compactness**: Extract a *finite* subcover
4. **Take the minimum**: Since you now have only finitely many balls, you can take the minimum of their radii to get a uniform \`δ\`!

**New Definitions**:

Open ball of radius \`r\` around \`x\`:

\`def Ball (x : ℝ) (r : ℝ) : Set ℝ := Ioo (x - r) (x + r)\`

Compactness (every open cover has a finite subcover):

\`def IsCompact (S : Set ℝ) : Prop :=
  ∀ (ι : Type) (xs : ι → ℝ) (δs : ι → ℝ), (∀ i, 0 < δs i) →
    (S ⊆ ⋃ i, Ball (xs i) (δs i)) →
    ∃ (V : Finset ι), S ⊆ ⋃ i ∈ V, Ball (xs i) (δs i)\`

**The Magic**: The index type \`ι\` can be *anything* - natural numbers, real numbers, even uncountable sets. But compactness guarantees we can always reduce to a finite subcover!

**Key Tools**:
- \`mem_Union\`: \`(x ∈ ⋃ i, s i) ↔ ∃ i, x ∈ s i\`
- \`FinMinPos\`: From finitely many positive numbers, you can extract a positive lower bound

**Your Mission**: Prove that continuous + compact = uniformly continuous!
`,
  conclusion: `
# The Grand Synthesis!

You've just completed one of the most beautiful proofs in mathematics! You've shown that **continuity + compactness = uniform continuity**.

**What Makes This Proof Extraordinary**:
- **Local to Global**: You started with local information (continuity at each point) and used compactness to extract global information (uniform continuity everywhere)
- **Infinite to Finite**: The proof converts an infinite covering problem into a finite one, where you can actually compute minima
- **Abstract to Concrete**: You used the abstract concept of compactness to solve the concrete problem of finding a uniform δ

**The Complete Picture**: Combining all three levels, you've now proved the fundamental chain:

\`Continuous on [a,b] → Uniformly Continuous on [a,b] → Integrable on [a,b]\`

**Why This Matters Historically**:
- **Riemann** (1850s) defined integration but couldn't rigorously prove when it worked
- **Cauchy** earlier made errors by missing the uniformity requirement
- **Heine-Borel** (1890s-1900s) finally clarified compactness
- **Lebesgue** (1900s) built on these foundations for modern integration theory

**The Topological Revolution**: Before topology, mathematicians did analysis with intuition and clever tricks. Compactness gave them the 'right' framework to make rigorous arguments. This is why closed bounded intervals \`[a,b]\` are so special in calculus - they're exactly the compact sets in \`ℝ\`!

**Real-World Impact**: Every time you compute \`∫₀¹ f(x)dx\` in calculus and trust that it exists, you're using today's theorem. Every continuous function on \`[0,1]\` is integrable because \`[0,1]\` is compact!

**Looking Forward**: You've seen how topology (compactness) illuminates analysis (integration). This pattern repeats throughout mathematics - the 'right' abstract framework often makes concrete problems much clearer. Welcome to the power of mathematical abstraction!
`,
};

export default level;
