// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L7Pset/L7Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L7Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L7Pset_2",
  statement: `(a b : ℕ → ℝ) (L M : ℝ) (ha : SeqLim a L) (hb : SeqLim b M) (hLM : L < M) :
  ∃ N, ∀ n ≥ N, a n < b n`,
  objects: "(a b : ℕ → ℝ) (L M : ℝ)",
  assumptions: "(ha : SeqLim a L) (hb : SeqLim b M) (hLM : L < M)",
  goal: "∃ N, ∀ n ≥ N, a n < b n",
  introduction: `# Problem 2

Suppose that sequences \`a b : ℕ → ℝ\` converge to \`L\` and \`M\`, resp, with \`L < M\`. Show that
eventually, \`a n < b n\`.

`,
  conclusion: "Done.",
};

export default level;
