// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L7Pset/L7Pset3.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L7Pset",
  level: 3,
  name: "Problem 3",
  theoremName: "L7Pset_3",
  statement: `(x y : ℝ) :
  |(|x| - |y|)| ≤ |x - y|`,
  objects: "(x y : ℝ)",
  goal: "|(|x| - |y|)| ≤ |x - y|",
  introduction: `# Problem 3

Prove \`abs_Lipschitz\`, obviously without referring to that theorem!
(Hint: you'll want to break things into cases according to whether \`0 ≤ x\` or not,
then systematically use \`abs_of_nonneg\` and \`abs_neg\`...)

`,
  conclusion: "Done.",
};

export default level;
