// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L7Pset/L7Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L7Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L7Pset_1",
  statement: `(a : ℕ → ℝ) (L : ℝ) (ha : SeqLim a L) (hL : L ≠ 0) :
  ∃ N, ∀ n ≥ N, |a n| ≤ 2 * |L|`,
  objects: "(a : ℕ → ℝ) (L : ℝ)",
  assumptions: "(ha : SeqLim a L) (hL : L ≠ 0)",
  goal: "∃ N, ∀ n ≥ N, |a n| ≤ 2 * |L|",
  introduction: `# Problem 1

Suppose that a sequence \`a : ℕ → ℝ\` converges to \`L ≠ 0\`. Show that eventually \`|a n|\` is at most
\`2|L|\`.

`,
  conclusion: "Done.",
};

export default level;
