// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L24Levels/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture24",
  level: 1,
  name: "Heine-Borel Theorem: Part 1a",
  theoremName: "Lecture24_1",
  statement: "(S : Set ℝ) (hcomp : IsCompact S) : ∃ M, ∀ s ∈ S, |s| < M",
  objects: "(S : Set ℝ) (hcomp : IsCompact S)",
  goal: "∃ M, ∀ s ∈ S, |s| < M",
  introduction: `
# Level 1: Heine-Borel Theorem: Part 1a

**The Goal**: We're starting our formal proof of the famous Heine-Borel theorem. First up: every compact set is bounded.

**The Strategy**: Remember that compactness means "every open cover has a finite subcover." To show a set is bounded, we need to trap it inside some big ball. Here's the clever idea:

1. **Create an infinite cover**: Cover the entire real line with balls \`Ball(0, 1)\`, \`Ball(0, 2)\`, \`Ball(0, 3)\`, etc. These definitely cover any set \`S\`.

2. **Extract a finite subcover**: Since \`S\` is compact, only finitely many of these balls are needed to cover \`S\`.

3. **Take the maximum**: The largest radius among these finitely many balls gives us our bound!

**Why This Works**: If \`S\` can be covered by balls of radii \`1, 3, 7, 12\` (for example), then every point in \`S\` has absolute value less than \`max(1, 3, 7, 12) = 12\`.

**Key Tool**: The \`FinMax\` lemma guarantees that any finite collection of real numbers has a maximum:

\`lemma FinMax (ι : Type) (V : Finset ι) (δs : ι → ℝ) :
    ∃ δ, ∀ i ∈ V, δs i ≤ δ\`

**Your Mission**: Formalize this intuitive argument. Use the balls \`Ball(0, n+1)\` for \`n : ℕ\`, apply compactness to get a finite subcover, then use \`FinMax\` to extract the bound!
`,
  conclusion: `
# First Half Complete!

You've just proved that **compact ⟹ bounded**! This is the first half of one direction of the Heine-Borel theorem.

**What Made This Proof Beautiful**:
- **Infinite to Finite Magic**: You started with infinitely many balls covering all of ℝ, but compactness let you reduce to just finitely many balls covering your set \`S\`.
- **Constructive Bound**: Your proof doesn't just say "a bound exists" - it gives you an explicit bound as the maximum radius of the finite subcover.
- **Archimedean Foundation**: The proof relies on the fact that balls \`Ball(0, n+1)\` eventually cover any point, which is essentially the Archimedean property of ℝ.

**The Bigger Picture**: You've shown that compactness prevents sets from "escaping to infinity." No matter how a compact set tries to spread out, it must stay within some finite ball.

**What's Next**: In Level 2, you'll prove that compact sets are also **closed**. This is trickier - you'll need to show that if a point is outside your compact set, then there's a whole ball around that point that stays outside. The key insight will be using compactness to create "uniform separation" between the outside point and your set.

**Historical Note**: This direction (compact ⟹ closed and bounded) is actually the easier direction of Heine-Borel. The hard work comes later when we prove the converse: closed and bounded ⟹ compact. That's where we'll need the deep structure of ℝ!

You're building the foundation for understanding why [a,b] intervals are so special in calculus!
`,
};

export default level;
