// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L24Levels/L02.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture24",
  level: 2,
  name: "Heine-Borel Theorem: Part 1b",
  theoremName: "Lecture24_2",
  statement: "(S : Set ℝ) (hcomp : IsCompact S) : IsClosed S",
  objects: "(S : Set ℝ) (hcomp : IsCompact S)",
  goal: "IsClosed S",
  introduction: `
# Level 2: Heine-Borel Theorem: Part 1b

**The Goal**: Complete the first direction of Heine-Borel by proving that every compact set is closed.

**New Topology Vocabulary**:
- **Open Set**: \`IsOpen S := ∀ x ∈ S, ∃ δ > 0, Ball x δ ⊆ S\`
  - Translation: "Around every point in \`S\`, there's a whole ball that stays inside \`S\`"
  - Think: "No boundary points belong to the set"
- **Closed Set**: \`IsClosed S := IsOpen Sᶜ\`
  - Translation: "The complement is open"
  - Think: "All boundary points belong to the set"

**The Challenge**: To prove \`S\` is closed, we need to prove \`Sᶜ\` is open. That means: for any point \`y ∉ S\`, we need to find a ball around \`y\` that stays completely outside \`S\`.

**The Strategy - Separation by Compactness**:
1. **Local Separation**: For each point \`x ∈ S\`, the distance \`|y - x|\` is positive (since \`y ∉ S\`). Create a ball around \`x\` of radius \`|y - x|/2\` - this ball contains \`x\` but can't reach \`y\`.

2. **Covering**: These balls cover \`S\`, so by compactness, finitely many suffice.

3. **Uniform Separation**: Take the minimum of the finitely many separating distances. This gives you a uniform \`δ > 0\` such that \`Ball(y, δ)\` stays away from all of \`S\`.

**Why This Works**: You're using compactness to convert "local separation" (each point in \`S\` is some positive distance from \`y\`) into "uniform separation" (there's a single \`δ\` that works everywhere).

**Your Mission**: Formalize this separation argument to show that \`Sᶜ\` is open!
`,
  conclusion: `
# Compactness ⟹ Closed and Bounded: Complete!

Excellent! You've just proved that **compact ⟹ closed**. Combined with Level 1, you've now established the full first direction of Heine-Borel:

**Compact ⟹ Closed and Bounded** ✓

**What Made This Proof Ingenious**:
- **The Separation Trick**: The key insight was using balls of radius \`|y - x|/2\` around points in \`S\`. These balls contain points of \`S\` but can never reach the outside point \`y\`.
- **Local to Uniform**: You converted the fact that \`y\` is separated from each individual point in \`S\` into uniform separation from the entire set \`S\`. This is compactness at its finest!
- **Finite Extraction**: Once again, compactness let you reduce an infinite problem (separation from all points in \`S\`) to a finite one (separation from finitely many covering balls).

**The Geometric Picture**: Imagine trying to "push" the outside point \`y\` into the compact set \`S\`. The proof shows this is impossible - there's always a "safety buffer" around \`y\` that keeps it separated from \`S\`.

**Why This Direction Is "Easy"**: Compactness gives you such strong control (every cover reduces to a finite subcover) that proving additional properties becomes manageable. The hard direction will be the converse!

**What's Next**: Now comes the serious work. In Level 3, you'll prove the **Least Upper Bound Property** of ℝ - every bounded set has a supremum. This fundamental property of the real numbers is what makes the converse direction possible.

**Looking Ahead**: Levels 4-5 will prove **Closed and Bounded ⟹ Compact**. This is where the real analysis gets deep, and you'll see why the completeness of ℝ matters!

The easy direction is done - now for the hard one! 🚀
`,
};

export default level;
