// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L24Levels/L03.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture24",
  level: 3,
  name: "Least Upper Bound Property",
  theoremName: "Lecture24_3",
  statement: "HasLUB_of_BddNonempty {S : Set ℝ} (hS : S.Nonempty) {M : ℝ} (hM : IsUB S M) : ∃ L, IsLUB S L",
  objects: "{S : Set ℝ} {M : ℝ}",
  assumptions: "(hS : S.Nonempty) (hM : IsUB S M)",
  goal: "∃ L, IsLUB S L",
  introduction: `
# Level 3: Least Upper Bound Property

**The Big Picture**: We're taking a detour into the deep structure of ℝ itself. To prove that closed bounded sets are compact, we need a fundamental property (that does not hold for ℚ!): **every bounded set has a supremum**.

**New Definitions**:
- **Upper Bound**: \`IsUB S (M : ℝ) := ∀ s ∈ S, s ≤ M\`
  - \`M\` sits above every point in \`S\`
- **Least Upper Bound**: \`IsLUB S L := IsUB S L ∧ ∀ M, IsUB S M → L ≤ M\`
  - \`L\` is an upper bound, and no smaller number is an upper bound

**The Proof Strategy - Bisection**:
We'll construct a sequence of nested intervals \`[aₙ, bₙ]\` that shrink to the supremum. Here's where Lean's **dependent types** shine:

\`let ab : ∀ (n : ℕ), {p : ℝ × ℝ //
  (p.1 ∈ S) ∧ IsUB S p.2 ∧ p.1 ≤ p.2 ∧ p.2 - p.1 ≤ (M - s₀) / 2^n}\`

This type says: "For each \`n\`, give me a pair \`(aₙ, bₙ)\` such that:
- \`aₙ ∈ S\` (so the left endpoint is achievable)
- \`bₙ\` is an upper bound for \`S\`
- \`aₙ ≤ bₙ\` (it's a valid interval)
- The interval length shrinks by half each time"

**The Inductive Construction**:
- **Base case**: Start with the \`s₀ ∈ S\` guaranteed by nonemptyness of \`S\`, and given upper bound \`M\`
- **Inductive step**: Given interval \`[aₙ, bₙ]\`, look at midpoint \`m = (aₙ + bₙ)/2\`
  - If \`m\` is an upper bound for \`S\`, set \`[aₙ₊₁, bₙ₊₁] = [aₙ, m]\`
  - If not, find some \`s ∈ S\` with \`s > m\`, set \`[aₙ₊₁, bₙ₊₁] = [s, bₙ]\`

**Dependent Types Magic**: The type system *guarantees* that our construction maintains all necessary properties at each step. We're not just building sequences - we're building sequences *with proofs* that they satisfy our constraints!

**Your Mission**: Implement this bisection algorithm and prove that the limit sequences converge to the least upper bound of \`S\`.
`,
  conclusion: `
# You've Just Proved ℝ is Complete!

Congratulations! You've just established one of the most fundamental properties of the real numbers: the **Least Upper Bound Property**. This is
another way to say that \`ℝ\` is "complete" - it has no gaps.

**What Made This Proof Special**:
- **Dependent Types Power**: Your proof showcased Lean's dependent type system at its best. The type \`ℕ → {p : ℝ × ℝ // ...}\` didn't just give you pairs of reals - it gave you pairs *with built-in proofs* that they satisfy all your constraints, and depend on the \`n : ℕ\`.
- **Constructive Algorithm**: Your bisection method doesn't just prove a supremum exists - it gives you an algorithm to compute it to arbitrary precision!
- **Induction on Steroids**: You weren't just proving a property for all \`n\` - you were constructing a sequence where each element depends on satisfying complex constraints involving the previous ones.

**Why This Property is Profound**:
- **\`ℚ\` Fails Here**: The rationals are missing "limit points" like √2. Your proof shows ℝ has no such gaps.
- **Topology Connection**: Completeness (LUB property) is what makes compact sets in ℝ so well-behaved.
- **Analysis Foundation**: Virtually every major theorem in real analysis depends on this completeness property.

**The Nested Interval Magic**: Your proof created intervals \`[aₙ, bₙ]\` with three beautiful properties:
1. Each \`aₙ ∈ S\` (reachable from below)
2. Each \`bₙ\` is an upper bound (unreachable from \`S\`)
3. \`bₙ - aₙ → 0\` (they squeeze together)

The limit of this squeeze is exactly the supremum!

**What's Coming**: Armed with the LUB property, you're now ready for the hard part of Heine-Borel. In Level 4, you'll prove that closed intervals \`[a,b]\` are compact. This will use your LUB property in a sophisticated way to show that any open cover can be reduced to a finite subcover.

**Historical Note**: This property was one of the last pieces needed to make calculus rigorous. Weierstrass, Dedekind, and Cantor all worked on different ways to construct ℝ with this completeness property in the 1870s.

You've just proved one of the crown jewels of real analysis! 👑
`,
};

export default level;
