// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L24Levels/L04.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture24",
  level: 4,
  name: "Heine-Borel Theorem: Part 2a",
  theoremName: "Lecture24_4",
  statement: "IsCompact_of_ClosedInterval {a b : ℝ} (hab : a < b) : IsCompact (Icc a b)",
  objects: "{a b : ℝ}",
  assumptions: "(hab : a < b)",
  goal: "IsCompact (Icc a b)",
  introduction: `
# Level 4: Heine-Borel Theorem: Part 2a

**The Hard Direction Begins**: Now for the converse! We need to prove that every closed bounded interval \`[a,b]\` is compact. This is where the real analysis gets deep.

**The Challenge**: Given any open cover of \`[a,b]\` by balls, we must extract a finite subcover. But how do you go from "every point is covered" to "finitely many balls suffice"?

**The Brilliant Strategy - Growing Intervals**:
We'll use your Least Upper Bound Property in a clever way:

1. **Define the "Good Set"**: Let \`S = {t ∈ [a,b] : [a,t] can be covered by finitely many balls}\`

2. **Show S is Bounded Above**: Obviously \`S ⊆ [a,b]\`, so \`b\` is an upper bound

3. **Show S is Non-empty**: Since our cover includes some ball containing \`a\`, we have \`a ∈ S\`

4. **Apply LUB**: By Level 3, \`S\` has a supremum \`L\`. The magic is showing \`L = b\`!

**The Key Insight**: If \`L < b\`, then \`L\` itself is covered by some ball in our covering. But balls have positive radius, so this ball covers not just \`L\` but some interval \`[L-δ, L+δ]\`. Since \`L = sup S\`, there's some \`t ∈ S\` with \`t > L-δ\`. Now we can:
- Cover \`[a,t]\` with finitely many balls (since \`t ∈ S\`)
- Cover \`[t, L+δ]\` with the single ball around \`L\`
- Combine them to cover \`[a, L+δ]\`

This means \`L+δ ∈ S\`, contradicting that \`L\` is an upper bound for \`S\`!

**Why This Works**: The proof exploits the tension between:
- **Discrete**: Finite covers (what we want to construct)
- **Continuous**: The supremum property (what Level 3 gives us)
- **Open**: Balls have positive radius (what creates the contradiction)

**Your Mission**: Implement this supremum-based argument. You'll need to carefully handle the cases and use the fact that every point in \`[a,b]\` is covered by some ball with positive radius.

This is where topology meets real analysis in its full glory!
`,
  conclusion: `
# The Crown Jewel Achievement!

You've just proved that **closed intervals are compact**! This is one of the most important theorems in all of real analysis.

**What Made This Proof Extraordinary**:
- **Three Mathematical Universes Colliding**: Your proof beautifully combined:
  - **Topology** (open covers and balls)
  - **Real Analysis** (supremums and the LUB property)
  - **Logic** (proof by contradiction)
- **The Supremum Trick**: The idea of considering the set of points where finite covering "reaches" was pure genius. You turned a global problem (covering all of \`[a,b]\`) into a supremum problem.
- **Positive Radius Magic**: The contradiction came from the fact that balls have positive radius - if you can finitely cover up to the supremum, the ball covering the supremum lets you "jump past" it.

**Why This Result is Fundamental**:
- **Calculus Foundation**: Every time you integrate a continuous function on \`[a,b]\`, you're using this theorem! Continuous functions on compact sets are uniformly continuous, hence integrable.
- **Optimization**: Every continuous function on \`[a,b]\` attains its maximum and minimum (extreme value theorem) - because compact sets are where continuous functions behave nicely.
- **Approximation Theory**: Polynomial approximation theorems (like Weierstrass) rely heavily on compactness of intervals.

**The Historical Significance**: This theorem was the missing piece that made 19th-century analysis rigorous. Before understanding compactness, mathematicians had intuitions about why closed intervals were "nice" but couldn't prove it.

**What's Left**: You've proved that all closed intervals are compact. Level 5 will extend this to prove that ANY closed and bounded set is compact, by showing that closed subsets of compact sets inherit compactness.

**The Payoff**: Once you complete Level 5, you'll have the complete Heine-Borel theorem:

\`S is compact ⟺ S is closed and bounded\`

You could in theory stop at this point, because closed intervals are what we were after for applications to convergence of Riemann sums and uniform continuity. But the full Heine-Borel theorem is a cornerstone of real analysis, so let's finish the job!

**Looking Back**: Your journey from compactness ⟹ boundedness (Level 1) to this deep result shows the power of mathematical abstraction. You've connected the discrete (finite covers), the continuous (supremums), and the topological (open sets) into one unified theory.

You're almost at the summit of one of mathematics' great theorems! 🏔️
`,
};

export default level;
