// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L24Levels/L05.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture24",
  level: 5,
  name: "Heine-Borel Theorem: Part 2b",
  theoremName: "Lecture24_5",
  statement: "IsCompact_of_ClosedSubset {S T : Set ℝ} (hST : S ⊆ T) (hT : IsCompact T) (hS : IsClosed S) : IsCompact S",
  objects: "{S T : Set ℝ}",
  assumptions: "(hST : S ⊆ T) (hT : IsCompact T) (hS : IsClosed S)",
  goal: "IsCompact S",
  introduction: `
# Level 5: Heine-Borel Theorem: Part 2b

**The Grand Finale**: We'll complete Heine-Borel by proving that any closed, bounded set is compact. The strategy is elegant: show that closed subsets of compact sets are compact, then use Level 4.

**New Lean Technology - Sum Types** 📦

Before diving into the proof, you need to master Lean's **disjoint union** (sum type):

**What is \`α ⊕ β\`?**: It's the "either \`α\` or \`β\`" type - every element is either from type \`α\` or from type \`β\`, but not both. Think of it as two boxes labeled "Left" and "Right":

\`α ⊕ β = {Sum.inl a : a ∈ α} ∪ {Sum.inr b : b ∈ β}\`

**Note**:
- \`Sum.inl a\` puts element \`a : α\` into the "left" side
- \`Sum.inr b\` puts element \`b : β\` into the "right" side

**Pattern Matching with \`match\`**: To make a function on a sum type, use \`match\`:

\`let f : α ⊕ β → γ := fun x ↦
  match x with
  | Sum.inl a => ... -- handle the α case
  | Sum.inr b => ... -- handle the β case\`

**Case Analysis with \`cases\`**: When arguing about where an element of a sum type came from, use \`cases\`:

\`cases x with
| inl a => ... -- when x came from α
| inr b => ... -- when x came from β\`

**Extracting Components**: If \`s : Finset (α ⊕ β)\`, then:
- \`s.lefts : Finset α\` extracts all the "left" elements
- \`a ∈ s.lefts ↔ Sum.inl a ∈ s\`

**Why Sum Types for This Proof?**

We need to handle TWO kinds of balls simultaneously:
1. **Original balls** (type \`ι\`) that cover our closed set \`S\`
2. **Avoidance balls** (type \`Sᶜ\`) that cover points outside \`S\`

The sum type \`ι ⊕ Sᶜ\` lets us create a unified covering system!

**The Strategy**:
1. Start with any covering of closed set \`S ⊆ T\` where \`T\` is compact
2. Since \`S\` is closed, \`Sᶜ\` is open - so each point in \`Sᶜ\` has a ball staying in \`Sᶜ\`
3. Use sum types to combine: original balls + avoidance balls = covering of all \`T\` (in fact, all of \`ℝ\`)
4. Apply compactness of \`T\` to get finite subcover
5. Extract just the "left" (original) balls to cover \`S\`, since avoidance balls don't touch \`S\`

**Your Mission**: Master sum types and use them to extend any covering of a closed subset to a covering of the whole compact set. This completes the Heine-Borel theorem!
`,
  conclusion: `
# 🎉 HEINE-BOREL THEOREM: COMPLETE! 🎉

You did it! You've just completed the proof of one of the most important theorems in all of mathematics:

**HEINE-BOREL THEOREM**: \`S ⊆ ℝ is compact ⟺ S is closed and bounded\`

**What You've Accomplished**:
- ✅ **Level 1**: Compact ⟹ Bounded
- ✅ **Level 2**: Compact ⟹ Closed
- ✅ **Level 3**: Least Upper Bound Property of ℝ
- ✅ **Level 4**: Closed Interval [a,b] is Compact
- ✅ **Level 5**: Closed Subset of Compact is Compact

**The Sum Type Mastery**: Your final proof showcased advanced Lean programming with sum types. You learned to:
- **Construct** disjoint unions \`α ⊕ β\`
- **Pattern match** with \`match\` and \`cases\`
- **Extract components** with \`Finset.lefts\`
- **Combine different index types** into unified covering systems

This isn't just theorem proving - it's sophisticated type-level programming!

**The Mathematical Journey**: You've traveled from elementary compactness through:
- **Topology** (open/closed sets, covers)
- **Real Analysis** (supremums, completeness of ℝ)
- **Logic** (proof by contradiction, case analysis)
- **Type Theory** (dependent types, sum types)

**Why This Theorem Changes Everything**:

🧮 **For Calculus**: Every continuous function on [a,b] is now guaranteed to be:
   - Uniformly continuous (by Level 23)
   - Integrable (Riemann sums converge)
   - Bounded and achieving max/min

📊 **For Analysis**: You can now easily check compactness just by verifying "closed and bounded" - no more wrestling with covers and subcovers!

🔬 **For Topology**: You've connected the abstract (compactness) with the concrete (closed + bounded), making topology applicable to real analysis.

**Historical Impact**: Your theorem unified 19th-century analysis. Before Heine (1872) and Borel (1895), mathematicians had intuitions about why [a,b] was special but couldn't prove it rigorously.

**The Complete Chain**: You can now trace the full logical chain:

\`f continuous on [a,b] → [a,b] compact (Heine-Borel)
                     → f uniformly continuous (Level 23)
                     → f integrable (Level 23)\`

**Looking Forward**: You've built the foundation for advanced analysis - measure theory, functional analysis, and differential geometry all build on compactness.

You've just proved one of the crown jewels of mathematics! Take a moment to appreciate the elegant interplay of topology, analysis, and logic you've mastered. 🏆

Welcome to the ranks of real analysts!
`,
};

export default level;
