// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1Pset/L1Pset5.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L1Pset",
  level: 5,
  name: "Problem 5",
  theoremName: "L1Pset_5",
  statement: `(p : ℝ → ℝ) (x : ℝ) (h1 : ∀ t, p (t) = t ^ 2 + 2 * t)
 (h2 : p (x) = 15)
 :
  ∃ b, x ^ 2 + 2 * x = b`,
  objects: "(p : ℝ → ℝ) (x : ℝ)",
  assumptions: "(h1 : ∀ t, p (t) = t ^ 2 + 2 * t) (h2 : p (x) = 15)",
  goal: "∃ b, x ^ 2 + 2 * x = b",
  introduction: `
# Problem 5

You've learned about adding hypotheses with \`have\`, and that you can call tactics not
just to act on the Goal, but  also on hypotheses, via adding \`at HypothesisName\` at the end.
You also know that calling the \`rewrite\` tactic with a hypothesis \`h : X = Y\` takes the *left hand side* \`X\` and replaces it by \`Y\`. But what if you needed instead to replace \`Y\`'s by \`X\`'s? We call that "backwards rewriting". The syntax for that is:

\`rewrite [← h]\`

or

\`rewrite [← h] at h2\`

to do it at some other hypothesis, \`h2\`. You get the backwards arrow by typing \\left,
that is, the backslash, then the word \`left\`, and then a space.

You may (or may not) find that useful in this problem.
`,
  conclusion: "Done.",
};

export default level;
