// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1Pset/L1Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L1Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L1Pset_2",
  statement: `:
 ∃ c, ∀ x y : ℝ, x ^ 2 + y ^ 2 = 2 → x * y = 1 → (x + y) ^ 2 = c`,
  goal: "∃ c, ∀ x y : ℝ, x ^ 2 + y ^ 2 = 2 → x * y = 1 → (x + y) ^ 2 = c",
  introduction: `
# Problem 2

In this problem you are asked to show that there is some \`c\` so that \`(x + y) ^ 2 = c\`, given that
\`x * y = 1\` and \`x ^ 2 + y ^ 2 = 2\`.

You will likely have a hard time solving this problem as is.
You surely can work out what value of
\`c\` you need. But if you try
\`ring_nf\`, you won't have control over
how the "normal form" chooses to
express things. In fact, the
left-hand side, \`(x + y) ^ 2\` will
turn into \`x * y * 2 + x ^ 2 + y ^ 2\`,
which is parsed in this order:

\`(((x * y) * 2) + x ^ 2) + y ^ 2\`

This means that you *will* be able to
\`rewrite [h2]\` successfully,
but then you will *not* be able to rewrite by \`h1\`, because the (invisible) parentheses  go the wrong way. (Hint: If you want to know how things are grouped but don't see parentheses, you can hover your cursor over the text in the Goal State, and Lean will show you the groupings. Try it!)

Now, in natural language, there are times when you might want to
record an auxiliary fact: "let's
*have* the fact that such and such ...". The Lean
syntax for this is as follows:

\`have NewFactName (Assumptions) : Conclusion := by Proof\`

That is, you first write \`have\`; then give
the new hypothesis a name; then include any
assumptions, like \`(x : ℝ)\`, meaning, \`x\`
is a real number, etc (the symbol \`ℝ\` is written with a backslash, then capital \`R\`, then space); then you put a colon,
and then state the conclusion; then you
put a colon-equals and the word \`by\`; and finally you give the proof.

For example, if you wanted to declare
the new fact that, say, for any real \`u\` and \`v\`,

\`(u + v) ^ 2 = (u ^ 2 + v ^ 2) + 2 * (u * v)\`

and you wanted to call this fact \`huv\` (a hypothesis on \`u\` and \`v\`),
and you wanted to prove this fact by
invoking the ring normal form tactic,
 then you would give Lean the command:

\`have huv (u v : ℝ) : (u + v) ^ 2 = (u ^ 2 + v ^ 2) + 2 * (u * v) := by ring_nf\`

This will add to your list of hypotheses
the fact: \`huv : ∀ (u v : ℝ), (u + v) ^ 2 = (u ^ 2 + v ^ 2) + 2 * (u * v)\`.

Something like this (if not exactly this)
will be useful to you in solving this problem.
`,
  conclusion: `Did you end up using \`huv\`?
And then \`specialize\`ing it with \`u\` and \`v\` replaced, respectively, by \`x\` and \`y\`?
Or did you think of going via the more direct route:
\`have hxy : (x + y) ^ 2 = (x ^ 2 + y ^ 2) + 2 * (x * y) := by ring_nf\`?`,
};

export default level;
