// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1Pset/L1Pset4.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L1Pset",
  level: 4,
  name: "Problem 4",
  theoremName: "NegOnePowDNC",
  theoremStatement: `(a : ℕ → ℝ) (ha : ∀ n, a n = (-1) ^ n) : ¬ SeqConv a`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ n, a n = (-1) ^ n)",
  goal: "¬ SeqConv a",
  introduction: `
# Problem 4

Prove that $(-1)^n$ does not converge.
`,
  conclusion: "Done.",
};

export default level;
