// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1Pset/L1Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L1Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "FunContComp",
  theoremStatement: `(f g : ℝ → ℝ) (hf : FunCont f) (hg : FunCont g) :
 FunCont (f ∘ g)`,
  objects: "(f g : ℝ → ℝ)",
  assumptions: "(hf : FunCont f) (hg : FunCont g)",
  goal: "FunCont (f ∘ g)",
  introduction: `
# Problem 2: Prove that if $f$ and $g$ are continuous functions, then the composition $f$ ∘ $g$ is also continuous.`,
  conclusion: `Did you end up using \`huv\`?
And then \`specialize\`ing it with \`u\` and \`v\` replaced, respectively, by \`x\` and \`y\`?
Or did you think of going via the more direct route:
\`have hxy : (x + y) ^ 2 = (x ^ 2 + y ^ 2) + 2 * (x * y) := by ring_nf\`?`,
};

export default level;
