// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1Pset/L1Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L1Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L1Pset_1",
  statement: `(f : ℝ → ℝ) (h : ∀ u, f (u) = 2 * u + 1) :
  ∃ a, f (3) = a`,
  objects: "(f : ℝ → ℝ)",
  assumptions: "(h : ∀ u, f (u) = 2 * u + 1)",
  goal: "∃ a, f (3) = a",
  introduction: "# Problem 1",
  conclusion: "Done.",
};

export default level;
