// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1Pset/L1Pset3.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L1Pset",
  level: 3,
  name: "Problem 3",
  theoremName: "OneOverNLimit",
  theoremStatement: `(a : ℕ → ℝ) (ha : ∀ n, a n = 1 / n) :
 SeqLim a 0`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ n, a n = 1 / n)",
  goal: "SeqLim a 0",
  introduction: `
# Problem 3

Now prove that the limit of the sequence $a_n = \\frac{1}{n}$ is $0$.
`,
  conclusion: "Done.",
};

export default level;
