// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L1Pset/L1Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L1Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "LimConstFun",
  theoremStatement: `(f : ℝ → ℝ) (c : ℝ) (hf : ∀ x, f (x) = c) :
  ∀ x, FunLimAt f c x`,
  objects: "(f : ℝ → ℝ) (c : ℝ)",
  assumptions: "(hf : ∀ x, f (x) = c)",
  goal: "∀ x, FunLimAt f c x",
  introduction: "# Prove that the constant function $f(x) = c$ has limit $c$ at every point.",
  conclusion: "Done.",
};

export default level;
