// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L25Levels/L02.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture25",
  level: 2,
  name: "Intermediate Value Theorem",
  theoremName: "Lecture25_2",
  statement: `IVT {f : ℝ → ℝ} (hf : FunCont f) {a b : ℝ} (hab : a < b)
    (hfa : f a < 0) (hfb : 0 < f b): ∃ c ∈ Ioo a b, f c = 0`,
  objects: "{f : ℝ → ℝ} {a b : ℝ}",
  assumptions: "(hf : FunCont f) (hab : a < b) (hfa : f a < 0) (hfb : 0 < f b)",
  goal: "∃ c ∈ Ioo a b, f c = 0",
  introduction: `
# Level 2 **BIG BOSS**: Intermediate Value Theorem

Welcome to the grand finale! We end our journey through formal real analysis with mathematics' most "obvious" theorem—one so intuitive that it was used without proof for over **2000 years**.

**The Intermediate Value Theorem**: If a function \`f\` is continuous on a closed interval \`[a, b]\`, with \`f(a) < 0\` and \`f(b) > 0\`, then there exists some \`c ∈ (a, b)\` such that \`f(c) = 0\`.

*Translation*: A continuous function that changes sign must cross zero somewhere.

**Why is this the "greatest" theorem?** Because it captures something profound about the real numbers that we take for granted: there are **no gaps**. Unlike the rationals ℚ (where \`f(x) = x² - 2\` changes sign but never equals zero), the reals ℝ are **complete**.

**Historical irony**: Ancient Greeks used this theorem in geometric constructions. Euler applied it freely. Even Bolzano and Cauchy assumed it initially. Yet the first rigorous proof wasn't given until 1817—after calculus had been developed for 150 years!

**Why so hard to prove?** Because it requires the **Least Upper Bound Principle**—the very completeness of ℝ that distinguishes it from ℚ. This "obvious" theorem actually encapsulates the deepest property of real numbers.

Your proof will use *every major tool* we've built: suprema, continuity, proof by contradiction, and the intricate dance between topology and analysis. Ready for the ultimate challenge?
`,
  conclusion: `
**COURSE COMPLETE!** You've just proven the most fundamental theorem about continuous functions and conquered the final boss of Real Analysis: The Game.

**What you accomplished**: You proved that continuous functions have no "jumps"—a property so basic that mathematicians assumed it for millennia without proof. Your proof revealed the intimate connection between:
- **Topology** (continuity of functions)
- **Order** (the structure of real numbers)
- **Completeness** (the Least Upper Bound Principle)

**The deeper significance**: This "obvious" theorem actually characterizes what makes ℝ special. In ℚ, continuous functions CAN change sign without crossing zero (like x² - 2). The IVT is really a theorem about the **completeness** of the real line—there are no gaps.

**Your proof technique** was a masterpiece of mathematical reasoning: you used the supremum of a carefully chosen set, then eliminated both f(c) < 0 and f(c) > 0 through elegant contradictions involving continuity. This is analysis at its finest.

**Historical triumph**: You've now rigorously proven what Archimedes used, what Newton assumed, and what Euler took for granted. The theorem they used intuitively for centuries finally has the rigorous foundation it deserves.

**Congratulations!** You've mastered the interplay between limits, continuity, completeness, and proof—the very heart of real analysis. From ε-δ definitions to the deepest theorems about ℝ, you've built mathematics from the ground up.

*Welcome to the ranks of real analysts.*
`,
};

export default level;
