// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L20Levels/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture20",
  level: 1,
  name: "Limits of Functions",
  theoremName: "Lecture20_1",
  statement: `:
    ∃ L, FunLimAt (fun x ↦ (x^2 - 1)/(x - 1)) L 1`,
  goal: "∃ L, FunLimAt (fun x ↦ (x^2 - 1)/(x - 1)) L 1",
  introduction: `
# Level 1: Introduction to Function Limits

Welcome to Lecture 20! We now shift our focus from sequences to **functions**. Just as we studied limits of sequences, we can study limits of functions as the input approaches a particular point.

## The Definition

**Definition (\`FunLimAt\`):** We say that \`f\` has limit \`L\` at \`x = c\` if:
\`\`\`
∀ ε > 0, ∃ δ > 0, ∀ x ≠ c, |x - c| < δ → |f x - L| < ε
\`\`\`

This is written \`FunLimAt f L c\`. (First the function, then the limit, then "at" \`x = c\`.)

**Reading the definition:** For *every* tolerance \`ε\` around the output value \`L\`, there exists a distance \`δ\` around the input value \`c\` such that whenever \`x\` is within \`δ\` of \`c\` (but not equal to \`c\`), the function value \`f(x)\` is within \`ε\` of \`L\`.

## The Intuition

The key difference from sequence limits is the condition \`x ≠ c\`. We care about what happens *near* c, but not at all about what happens *at* c. The function might not even be defined at \`c\`!

This is exactly what happens with the classic example:

\`f(x) = (x² - 1)/(x - 1)\`

At \`x = 1\`, the function is "undefined" (because it's \`0/0\`; in Lean, this is equal to \`0\`). But for \`x ≠ 1\`, we can factor:

\`f(x) = (x² - 1)/(x - 1) = (x - 1)(x + 1)/(x - 1) = x + 1\`

So as x approaches 1, \`f(x)\` approaches some constant \`L\`. Your job: figure out \`L\`, and prove that it's the limit!

## Your Challenge

Prove that there exists a limit \`L\` such that:

\`FunLimAt (fun x ↦ (x^2 - 1)/(x - 1)) L 1\`

In other words, prove that the function \`f(x) = (x² - 1)/(x - 1)\` has *some* limit as \`x\` approaches \`1\`.

`,
  conclusion: `
## What We've Learned

This first example captures the essence of function limits:

- The limit is about **behavior near a point**, not at the point itself
- The function \`f(x) = (x² - 1)/(x - 1)\` is undefined at \`x = 1\` (in standard mathematics), yet the limit exists!
- The algebra works out beautifully: for \`x ≠ 1\`, we can simplify the expression
- The \`ε\`-\`δ\` definition formalizes the intuitive idea of "getting arbitrarily close"

Notice how simple our choice of \`δ\` was: we just took \`δ = ε\`! This is because after simplification, the difference \`|f(x) - L|\` equals exactly \`|x - c|\`. In more complicated examples (like the next level), we'll need to be more clever with our choice of \`δ\`.

**Key insight:** Limits care about *tendency*, not *destination*.

The real power of this definition becomes clear when we realize that we can study the behavior of functions at points where they're not even defined. This is exactly what makes calculus work—derivatives are limits of difference quotients that are undefined when \`h = 0\`!
`,
};

export default level;
