// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 1,
  name: "DiffOfSeries",
  theoremName: "L18Pset_1",
  statement: `(a : ℕ → ℝ) {n m : ℕ} (hmn : n ≤ m) :
  Series a m - Series a n = ∑ k ∈ Ico n m, a k`,
  objects: "(a : ℕ → ℝ) {n m : ℕ}",
  assumptions: "(hmn : n ≤ m)",
  goal: "Series a m - Series a n = ∑ k ∈ Ico n m, a k",
  introduction: `
# Level 1: \`DiffOfSeries\`

Prove \`DiffOfSeries\`.

## New Theorem: \`sum_Ico_succ\`.

`,
  conclusion: `
`,
};

export default level;
