// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L02.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 2,
  name: "Series_abs_add",
  theoremName: "L18Pset_2",
  statement: `(a : ℕ → ℝ) {n m : ℕ} (hmn : n ≤ m) :
  |∑ k ∈ Ico n m, a k| ≤ ∑ k ∈ Ico n m, |a k|`,
  objects: "(a : ℕ → ℝ) {n m : ℕ}",
  assumptions: "(hmn : n ≤ m)",
  goal: "|∑ k ∈ Ico n m, a k| ≤ ∑ k ∈ Ico n m, |a k|",
  introduction: `
# Level 2: \`Series_abs_add\`

Prove \`Series_abs_add\`:

`,
  conclusion: `
`,
};

export default level;
