// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L03.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 3,
  name: "AntitoneLimitBound",
  theoremName: "L18Pset_3",
  statement: `{a : ℕ → ℝ} (ha : Antitone a) {L : ℝ} (aLim : SeqLim a L) : ∀ n,
  L ≤ a n`,
  objects: "{a : ℕ → ℝ} {L : ℝ}",
  assumptions: "(ha : Antitone a) (aLim : SeqLim a L)",
  goal: "∀ n, L ≤ a n",
  introduction: `
# Level 3: \`AntitoneLimitBound\`

Prove \`AntitoneLimitBound\`:

`,
  conclusion: `
`,
};

export default level;
