// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L04.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 4,
  name: "CoherenceOfReals",
  theoremName: "L18Pset_4",
  statement: "{a b : ℕ → ℝ} {L M : ℝ} (ha : SeqLim a L) (hb : SeqLim b M) (hab : SeqLim (fun n ↦ a n - b n) 0) : L = M",
  objects: "{a b : ℕ → ℝ} {L M : ℝ}",
  assumptions: "(ha : SeqLim a L) (hb : SeqLim b M) (hab : SeqLim (fun n ↦ a n - b n) 0)",
  goal: "L = M",
  introduction: `
# Level 4: \`CoherenceOfReals\`

Prove \`CoherenceOfReals\`:

`,
  conclusion: `
`,
};

export default level;
