// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L05.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 5,
  name: "SeqEvenOdd",
  theoremName: "L18Pset_5",
  statement: `{a : ℕ → ℝ} {L : ℝ} (ha2n : SeqLim (fun n ↦ a (2 * n)) L)
(ha2np1 : SeqLim (fun n ↦ a (2 * n + 1)) L) : SeqLim a L`,
  objects: "{a : ℕ → ℝ} {L : ℝ}",
  assumptions: "(ha2n : SeqLim (fun n ↦ a (2 * n)) L) (ha2np1 : SeqLim (fun n ↦ a (2 * n + 1)) L)",
  goal: "SeqLim a L",
  introduction: `
# Level 5: \`SeqEvenOdd\`

Prove \`SeqEvenOdd\`:

## New theorem: \`even_or_odd\`

`,
  conclusion: `
`,
};

export default level;
