// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L06.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 6,
  name: "MonotoneSeriesEven",
  theoremName: "L18Pset_6",
  statement: `{a : ℕ → ℝ} (ha : Antitone a) (apos : ∀ n, 0 ≤ a n) :
  Monotone (fun n ↦ ∑ k ∈ range (2 * n), (-1)^k * a k)`,
  objects: "{a : ℕ → ℝ}",
  assumptions: "(ha : Antitone a) (apos : ∀ n, 0 ≤ a n)",
  goal: "Monotone (fun n ↦ ∑ k ∈ range (2 * n), (-1)^k * a k)",
  introduction: `
# Level 6: \`MonotoneSeriesEven\`

Prove \`MonotoneSeriesEven\`:

`,
  conclusion: `
`,
};

export default level;
