// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L07.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 7,
  name: "AntitoneSeriesOdd",
  theoremName: "L18Pset_7",
  statement: "{a : ℕ → ℝ} (ha : Antitone a) (apos : ∀ n, 0 ≤ a n) : Antitone (fun n ↦ ∑ k ∈ range (2 * n + 1), (-1)^k * a k)",
  objects: "{a : ℕ → ℝ}",
  assumptions: "(ha : Antitone a) (apos : ∀ n, 0 ≤ a n)",
  goal: "Antitone (fun n ↦ ∑ k ∈ range (2 * n + 1), (-1)^k * a k)",
  introduction: `
# Level 7: \`AntitoneSeriesOdd\`

Prove \`AntitoneSeriesOdd\`:

`,
  conclusion: `
`,
};

export default level;
