// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L08.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 8,
  name: "BddSeriesEven",
  theoremName: "L18Pset_8",
  statement: "{a : ℕ → ℝ} (ha : Antitone a) (apos : ∀ n, 0 ≤ a n) (n : ℕ) : ∑ k ∈ range (2 * n), (-1)^k * a k ≤ a 0",
  objects: "{a : ℕ → ℝ} (n : ℕ)",
  assumptions: "(ha : Antitone a) (apos : ∀ n, 0 ≤ a n)",
  goal: "∑ k ∈ range (2 * n), (-1)^k * a k ≤ a 0",
  introduction: `
# Level 8: \`BddSeriesEven\`

Prove \`BddSeriesEven\`:

You might find the theorem \`sum_range_succ'\` useful. It is like \`sum_range_succ\`, but
pulls out the first term instead of the last.

`,
  conclusion: `
`,
};

export default level;
