// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L09.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 9,
  name: "BddSeriesOdd",
  theoremName: "L18Pset_9",
  statement: "{a : ℕ → ℝ} (ha : Antitone a) (ha' : ∀ n, 0 ≤ a n) (n : ℕ) : 0 ≤ ∑ k ∈ range (2 * n + 1), (-1)^k * a k",
  objects: "{a : ℕ → ℝ} (n : ℕ)",
  assumptions: "(ha : Antitone a) (ha' : ∀ n, 0 ≤ a n)",
  goal: "0 ≤ ∑ k ∈ range (2 * n + 1), (-1)^k * a k",
  introduction: `
# Level 9: \`BddSeriesOdd\`

Prove \`BddSeriesOdd\`:

`,
  conclusion: `
`,
};

export default level;
