// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L18Pset/L10.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L18Pset",
  level: 10,
  name: "DiffGoesToZero",
  theoremName: "L18Pset_10",
  statement: "{a : ℕ → ℝ} (aLim : SeqLim a 0) : SeqLim (fun n ↦ ∑ k ∈ range (2 * n + 1), (-1)^k * a k - ∑ k ∈ range (2 * n), (-1)^k * a k) 0",
  objects: "{a : ℕ → ℝ}",
  assumptions: "(aLim : SeqLim a 0)",
  goal: "SeqLim (fun n ↦ ∑ k ∈ range (2 * n + 1), (-1)^k * a k - ∑ k ∈ range (2 * n), (-1)^k * a k) 0",
  introduction: `
# Level 10: \`DiffGoesToZero\`

Prove \`DiffGoesToZero\`:

`,
  conclusion: `
`,
};

export default level;
