// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L16Pset/L16Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L16Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L16Pset_1",
  statement: "(x : ℝ) (n : ℕ) : (1 - x) * ∑ k ∈ range n, x ^ k = 1 - x ^ n",
  objects: "(x : ℝ) (n : ℕ)",
  goal: "(1 - x) * ∑ k ∈ range n, x ^ k = 1 - x ^ n",
  introduction: `
# Problem 1: Finite geometric series

`,
  conclusion: "",
};

export default level;
