// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L16Pset/L16Pset3.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L16Pset",
  level: 3,
  name: "Problem 3",
  theoremName: "L16Pset_3",
  statement: "(a b c : ℕ → ℝ) (h : ∀ n, c n = a n + b n) : ∀ n, Series c n = Series a n + Series b n",
  objects: "(a b c : ℕ → ℝ)",
  assumptions: "(h : ∀ n, c n = a n + b n)",
  goal: "∀ n, Series c n = Series a n + Series b n",
  introduction: `
# Problem 3: Prove that the sum of two series is the series of the sum.

`,
  conclusion: "",
};

export default level;
