// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L16Pset/L16Pset2.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L16Pset",
  level: 2,
  name: "Problem 2",
  theoremName: "L16Pset_2",
  statement: "(a b : ℕ → ℝ) (c : ℝ) (hb : ∀ n, b n = c * a n) : ∀ n, Series b n = c * Series a n",
  objects: "(a b : ℕ → ℝ) (c : ℝ)",
  assumptions: "(hb : ∀ n, b n = c * a n)",
  goal: "∀ n, Series b n = c * Series a n",
  introduction: `
# Problem 2: Prove that multiplying a series by a constant scales its sum accordingly.

`,
  conclusion: "",
};

export default level;
