// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L11Pset/L11Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L11Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L11Pset_1",
  statement: `(a : ℕ → ℝ) (ha : ∀ n, a n = n)
      : ¬ ∃ σ, Subseq σ ∧ SeqConv (a ∘ σ)`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha : ∀ n, a n = n)",
  goal: "¬ ∃ σ, Subseq σ ∧ SeqConv (a ∘ σ)",
  introduction: `
# Problem 1:

Prove that the sequence \`a n = n\` has no convergent subsequence.

`,
  conclusion: "Done.",
};

export default level;
