// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L13Levels/L02_SubseqIterateNOTNEEDED.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture13",
  level: 1,
  name: "Iterated Subsequence",
  theoremName: "Lecture13_1",
  statement: `(σ : ℕ → ℕ) (hσ : ∀ n, n < σ n) (n₀ : ℕ) :
  Subseq (fun n ↦ σ^[n] n₀)`,
  objects: "(σ : ℕ → ℕ) (n₀ : ℕ)",
  assumptions: "(hσ : ∀ n, n < σ n)",
  goal: "Subseq (fun n ↦ σ^[n] n₀)",
  introduction: `
# Level 1: Iterated Subsequence

In the next level, we'll prove a theorem about \`Monotone\` subsequences
of certain sequences, for which this level is a warmup.

Here you'll prove the following. Assume that a sequence \`σ : ℕ → ℕ\` grows faster than the identity, \`σ n > n\`. For a fixed "base point" \`n₀ : ℕ\`, consider the "orbit of n₀ under σ", by which we mean: the sequence:

\`n₀, σ n₀, σ^[2] n₀, ...\`

In other words, start with \`n₀\` and keep applying \`σ\` iteratively (in Lean, we simply write the function: \`fun n ↦ σ^[n] n₀\`).

Goal: This orbit sequence is strictly increasing, that is, it is a \`Subseq\`.

## New theorem: \`subseq_of_succ\`

If you have a sequence \`σ : ℕ → ℕ\` and you know that
it increases from one term to its successor: \`σ n < σ (n + 1)\`,
then it's always strictly increasing, \`i < j → σ i < σ j\`; that is,
\`σ\` is a \`Subseq\`.

`,
  conclusion: "",
};

export default level;
