// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L5Levels/L01_skeleton.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture5",
  level: 1,
  name: "Doubling a Convergent Sequence",
  theoremName: "Lecture5_1",
  statement: `(a b : ℕ → ℝ) (L : ℝ)
    (h : SeqLim a L) (b_scaled : ∀ n, b n = 2 * a n) :
    SeqLim b (2 * L)`,
  objects: "(a b : ℕ → ℝ) (L : ℝ)",
  assumptions: "(h : SeqLim a L) (b_scaled : ∀ n, b n = 2 * a n)",
  goal: "SeqLim b (2 * L)",
  introduction: `
`,
  conclusion: "",
};

export default level;
