// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L4Pset/L4Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L4Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L4Pset_1",
  statement: `(a : ℕ → ℝ) (ha2n : ∀ n, a (2 * n) = 3 - 1 / n) (ha2np1 : ∀ n, a (2 * n + 1) = 1 + 1 / n)
  : ¬ SeqConv a`,
  objects: "(a : ℕ → ℝ)",
  assumptions: "(ha2n : ∀ n, a (2 * n) = 3 - 1 / n) (ha2np1 : ∀ n, a (2 * n + 1) = 1 + 1 / n)",
  goal: "¬ SeqConv a",
  introduction: `# Problem 1

Let \`a (n)\` be a sequence that alternates between
\`3 - 1 / n\` and \`1 + 1 / n\`. Prove that this sequence diverges.

**Hint:** You may wish to argue using \`N\` that's slightly
larger than the smallest possible value.

**Hint 2:** If your desired \`have\` is a consequence of two facts put together, you can separate them by a semicolon. For example, if you know that \`h : X = Y + Z\`,
and you want to add a hypothesis \`h' : |X - Y| = |Z|\`, which is a combination of rewriting by \`h\` and a ring operation, then you can say:

\`have h' : |X - Y| = |Z| := by rewrite [h]; ring_nf\`.

This might come in handy!...
`,
  conclusion: "Done.",
};

export default level;
