// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L13Pset/L13Pset1.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L13Pset",
  level: 1,
  name: "Problem 1",
  theoremName: "L13Pset_1",
  statement: `{X : Type*} [NormedField X] [LinearOrder X] [IsStrictOrderedRing X] [FloorSemiring X] (a : ℕ → X) (ha : UnBddPeaks a)
  : ∃ σ, Subseq σ ∧ Antitone (a ∘ σ)`,
  objects: "{X : Type*} [NormedField X] [LinearOrder X] [IsStrictOrderedRing X] [FloorSemiring X] (a : ℕ → X)",
  assumptions: "(ha : UnBddPeaks a)",
  goal: "∃ σ, Subseq σ ∧ Antitone (a ∘ σ)",
  introduction: `
# Problem 1:

Prove \`AntitoneSubseq_of_UnBddPeaks\`

## New theorem: \`Antitone_of_succ\`

`,
  conclusion: "",
};

export default level;
