// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L20Pset/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L20Pset",
  level: 1,
  name: "ContinuousIff I",
  theoremName: "L20Pset_1",
  statement: `(f : ℝ → ℝ) (c : ℝ) (hf : FunContAt f c) :
  FunLimAt f (f c) c`,
  objects: "(f : ℝ → ℝ) (c : ℝ)",
  assumptions: "(hf : FunContAt f c)",
  goal: "FunLimAt f (f c) c",
  introduction: `
# Level 1: ContinuousIff I

Prove the forward direction: If a function is continuous at \`x=c\`,
then its limit at \`x=c\` exists and is equal to \`f c\`.

`,
  conclusion: `
`,
};

export default level;
