// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L20Pset/L02.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L20Pset",
  level: 2,
  name: "ContinuousIff II",
  theoremName: "L20Pset_2",
  statement: `(f : ℝ → ℝ) (c : ℝ) (hf : FunLimAt f (f c) c) :
  FunContAt f c`,
  objects: "(f : ℝ → ℝ) (c : ℝ)",
  assumptions: "(hf : FunLimAt f (f c) c)",
  goal: "FunContAt f c",
  introduction: `
# Level 2: ContinuousIff II

Prove the backwards direction: If the limit at \`x=c\` of \`f\` exists and is equal to \`f c\`, then \`f\` is continuous at \`x=c\`.

`,
  conclusion: `
`,
};

export default level;
