// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L20Pset/L03.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L20Pset",
  level: 3,
  name: "Const Times Limit",
  theoremName: "L20Pset_3",
  statement: `(f : ℝ → ℝ) (c L k : ℝ) (hf : FunLimAt f L c) :
  FunLimAt (fun x ↦ k * f x) (k * L) c`,
  objects: "(f : ℝ → ℝ) (c L k : ℝ)",
  assumptions: "(hf : FunLimAt f L c)",
  goal: "FunLimAt (fun x ↦ k * f x) (k * L) c",
  introduction: `
# Level 3: Const Times Limit

Prove that if \`f → L\` as \`x → c\`, then \`k · f → k · L\`.
`,
  conclusion: `
`,
};

export default level;
