// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L20Pset/L04.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "L20Pset",
  level: 4,
  name: "Bounded Near Limit",
  theoremName: "L20Pset_4",
  statement: `(f : ℝ → ℝ) (c L : ℝ) (hf : FunLimAt f L c) :
  ∃ M > 0, ∃ δ > 0, ∀ x ≠ c, |x - c| < δ → |f x| < M`,
  objects: "(f : ℝ → ℝ) (c L : ℝ)",
  assumptions: "(hf : FunLimAt f L c)",
  goal: "∃ M > 0, ∃ δ > 0, ∀ x ≠ c, |x - c| < δ → |f x| < M",
  introduction: `
# Level 4: Bounded Near Limit

Prove that if \`f → L\` as \`x → c\`, then there is an \`M > 0\` such that
\`|f (x)| < M\` near \`c\`.
`,
  conclusion: `
`,
};

export default level;
