name = "LeanBlocksGame"
defaultTargets = ["LeanBlocksGame"]

[[require]]
name = "batteries"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.28.0"

[[lean_lib]]
name = "LeanBlocksGame"
